:: Characteristic Subgroups.
::  by Alex Nelson
::
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.


environ

 vocabularies MOD_4, CHAR, CARD_3, RLVECT_1, UPROOTS,
   RELAT_1, TARSKI, FUNCT_1, ZFMISC_1, XXREAL_0, XXREAL_1, FINSEQ_1,
   FINSET_1, NUMBERS, WELLORD1, SUBSET_1, XBOOLE_0, PARTFUN1,
   FUNCT_2, CARD_1, ARYTM_3, CQC_SIM1, ORDINAL1, PBOOLE,
   STRUCT_0, GROUP_1, GROUP_2, GROUP_3, GROUP_4, GROUP_5,
   GROUP_6, GROUP_7, BINOP_1, BINOP_2, ALGSTR_0, REALSET1, AUTGROUP, GR_CY_1, NATTRA_1,
   NAT_1, INT_2, SETFAM_1, NEWTON, PRE_TOPC, GROUP_10;
 constructors TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, RELAT_1, FUNCT_1,
   RELSET_1, PARTFUN1, FUNCT_2, FUNCOP_1, FINSEQ_1, FINSEQ_2, FINSOP_1,
   CARD_1, CARD_3, NUMBERS, REAL_1, SETWISEO,
   ARYTM_2, ARYTM_3, ORDINAL2, SQUARE_1,
   SETFAM_1, ORDINAL1,INT_1, INT_2, PBOOLE,
   XXREAL_2, XCMPLX_0, XXREAL_0, XREAL_0,  NAT_1, NAT_D,
   BINOP_1, BINOP_2, FINSET_1, STRUCT_0, ALGSTR_0, REALSET1, MONOID_0,
   GROUP_1, GROUP_2, GROUP_3, GROUP_4, GROUP_5, GROUP_6, PRALG_1, GROUP_7, GRSOLV_1,
   AUTGROUP, GROUP_9, GROUP_10, GR_CY_1, NEWTON;
 notations TARSKI, XBOOLE_0, SUBSET_1, XCMPLX_0, ORDINAL1, RELAT_1,
   FUNCT_1, RELSET_1, FUNCT_2, FUNCOP_1, SETWISEO, PARTFUN1,
   ZFMISC_1, CARD_1, CARD_3, INT_1, NAT_1, INT_2, ARYTM_2, ARYTM_3,
   FINSEQ_2, REAL_1, SETFAM_1, NUMBERS, MEMBERED, PBOOLE, BINOP_1,
   BINOP_2, FINSET_1, STRUCT_0, ALGSTR_0, XXREAL_0, FINSEQ_1, GROUP_1, GROUP_2,
   GROUP_3, GROUP_4, GROUP_5, REALSET1, GROUP_6, NAT_D, GRSOLV_1,
   AUTGROUP, GROUP_9, GROUP_10, GR_CY_1, NEWTON, PRALG_1, GROUP_7;
 registrations XBOOLE_0, RELAT_1, FUNCT_1, PARTFUN1, RELSET_1, FUNCT_2,
   ORDINAL1, FINSET_1, FINSEQ_1, NUMBERS, NAT_1, INT_1, INT_2, XCMPLX_0,
   ARYTM_3, XREAL_0, ARYTM_2, SETWISEO, CARD_1, NEWTON, FINSEQ_2,
   STRUCT_0, BINOP_1, GROUP_1, GROUP_2, GROUP_3, GROUP_6, GR_CY_1, GROUP_7;
 requirements BOOLE, SUBSET, NUMERALS, ARITHM, REAL;
 definitions TARSKI, SUBSET_1, FUNCT_1, FUNCT_2, ARYTM_2, FINSEQ_1, PRALG_1,
   GROUP_1, GROUP_3, GROUP_4, GROUP_5, GROUP_6, AUTGROUP, NEWTON, XXREAL_0, GROUP_7;
 equalities PARTFUN1, FINSET_1, BINOP_1, REALSET1, STRUCT_0, GROUP_2,
   GROUP_3, GROUP_4, GROUP_5, GROUP_6, GR_CY_1,
   ALGSTR_0, NEWTON, PRALG_1, GROUP_7;
 expansions TARSKI, FINSET_1, GROUP_1, GROUP_2, GROUP_6, STRUCT_0, BINOP_1,
   FUNCT_2, NEWTON, PRALG_1, GROUP_7;
 theorems
   TARSKI, SUBSET_1, RELSET_1, FUNCT_1, FUNCT_2, XBOOLE_0, CARD_1, RELAT_1,
   SETFAM_1, FINSEQ_3, PARTFUN1, ORDINAL1, CARD_3, PRALG_1, FINSEQ_1, FINSET_1,
   GROUP_1, GROUP_2, GROUP_3, GROUP_4, GROUP_5, GROUP_6, STRUCT_0, GRSOLV_1,
   AUTGROUP, GROUP_9, GROUP_10, GR_CY_1, XCMPLX_1, GROUP_7;
 schemes FUNCT_2, GROUP_4, FINSEQ_1, FRAENKEL;

begin :: Preparatory Work
reserve X for set;

registration
  let X;
  cluster id X -> onto;
  coherence;
end;

registration
  let X;
  cluster id X -> bijective;
  coherence;
end;

LmSubgroupEltTrans:
  for G being Group
  for H1,H2 being Subgroup of G
  for g being Element of G
  st g in H1 & H1 is Subgroup of H2
  holds g in H2 by GROUP_2:40;

theorem Th2:
  for G1,G2 being Group
  for H being Subgroup of G1
  for f being Homomorphism of G1,G2
  for h being Element of G1
  st h in H
  holds (f|H).h = f.h
proof
  let G1,G2 be Group;
  let H be Subgroup of G1;
  let f be Homomorphism of G1,G2;
  let h be Element of G1;
  assume h in H;
  then (f|(the carrier of H)).h = f.h by FUNCT_1:49;
  hence (f|H).h = f.h by GRSOLV_1:def 2;
end;

theorem Th4:
  for G being Group
  for H being Subgroup of G
  st (for a being Element of G holds H |^ a = H)
  holds H is normal Subgroup of G
proof
  let G be Group;
  let H be Subgroup of G;
  assume for a being Element of G holds H |^ a = H;
  then for a being Element of G holds the carrier of H |^ a = the carrier of H;
  then for a being Element of G holds the multMagma of H = H |^ a by GROUP_2:59;
  hence H is normal Subgroup of G by GROUP_3:def 13;
end;

theorem Th5:
  for X,Y being non empty set
  for f being Function of X,Y
  st f is bijective
  holds (f")" = f
proof
  let X,Y be non empty set;
  let f be Function of X,Y;
  assume A1: f is bijective;
  then A2: dom f = X & rng f = Y & f is one-to-one by FUNCT_2:def 3,def 1;
  reconsider g = f" as Function of Y,X by A2,FUNCT_2:25;
  A3: g is bijective by A1,GROUP_6:63;
  g is one-to-one & rng g = X implies g" is Function of X,Y
  by FUNCT_2:25;
  then reconsider h = g" as Function of X,Y by A3,FUNCT_2:def 3;

  for x being object st x in X holds h.x = f.x
  proof
    let x be object;
    assume x in X;
    then reconsider x as Element of X;
    consider y being object such that
    Z1: y = f.x;
    x = g.y by A1,Z1,FUNCT_2:26;
    then h.x = y by A1,Z1,FUNCT_2:26
            .= f.x by Z1;
    hence thesis;
  end;
  then h = f;
  hence (f")" = f;
end;

theorem Th6:
  for X,Y being non empty set
  for f being Function of X,Y
  st f is bijective
  for y being Element of Y
  holds f.((f").y) = y
proof
  let X,Y be non empty set;
  let f be Function of X,Y;
  assume A1: f is bijective;
  let y be Element of Y;
  f is onto by A1;
  then reconsider g = f" as Function of Y,X by A1,FUNCT_2:25;
  y = (g").(g.y) by A1,FUNCT_2:26
   .= f.((f").y) by Th5,A1;
  hence thesis;
end;

theorem Th7:
  for X,Y being non empty set
  for A being non empty Subset of X
  for x being Element of X
  st not x in A
  for f being Function of X,Y
  st f is one-to-one
  holds not f.x in (f .: A)
proof
  let X,Y be non empty set;
  let A be non empty Subset of X;
  let x be Element of X;
  assume A1: not x in A;
  let f be Function of X,Y;
  assume f is one-to-one;
  then A2: not ex a being object st x in dom f & a in dom f & a in A & f.a = f.x
  by A1, FUNCT_1:def 4;
  dom f = X by FUNCT_2:def 1;
  then A3: x in dom f;
  f.x in (f .: A) iff ex a being object st a in dom f & a in A & f.x = f.a
  by FUNCT_1:def 6;
  then f.x in (f .: A) implies contradiction by A2,A3;
  hence not (f.x in (f .: A));
end;

begin :: Nontrivial Groups and Subgroups
registration
  cluster non trivial for Group;
  existence
  proof
    reconsider G = multMagma (# REAL, addreal #) as Group by GROUP_1:3;
    take G;
    thus not (G is trivial);
  end;
end;
registration
  let G be Group;
  cluster trivial for Subgroup of G;
  existence
  proof
    take (1).G;
    thus thesis;
  end;
  let H be Subgroup of G;
  cluster trivial for Subgroup of H;
  existence
  proof
    take (1).H;
    thus thesis;
  end;
end;
registration
  let G be non trivial Group;
  cluster non trivial for Subgroup of G;
  existence
  proof
    reconsider H=G as Subgroup of G by GROUP_2:54;
    the carrier of H <> {1_G};
    hence thesis;
  end;

  cluster strict non trivial for Subgroup of G;
  existence
  proof
    set H = multMagma (#the carrier of G, the multF of G#);
    reconsider H as Group-like non empty multMagma;
    the multF of H = (the multF of G)||the carrier of H;
    then H is strict Subgroup of G & H is non trivial by GROUP_2:def 5;
    hence thesis;
  end;
end;

theorem Th8:
  for G being Group
  holds G is trivial iff the multMagma of G = (1).G
proof
  let G be Group;
  thus G is trivial implies the multMagma of G = (1).G
  proof
    assume G is trivial;
    then consider x being object such that
    A1: the carrier of G = {x};
    x = 1_G by A1, TARSKI:def 1;
    then the carrier of G = {1_G} by A1;
    then the carrier of G = the carrier of (1).G by GROUP_2:def 7;
    hence the multMagma of G = (1).G by GROUP_2:61;
  end;
  thus the multMagma of G = (1).G implies G is trivial;
  thus thesis;
end;

LmFiniteNontrivial:
  not INT.Group(2) is trivial
proof
  set G = INT.Group(2);
  A1: the carrier of G = Segm 2
                      .= 2 by ORDINAL1:def 17;
  the carrier of (1).G = {1_G} by GROUP_2:def 7
                      .= {0} by GR_CY_1:14
                      .= {} \/ {0}
                      .= succ 0 by ORDINAL1:def 1
                      .= 1;
  then the carrier of (1).G <> the carrier of G by A1;
  hence not INT.Group(2) is trivial by Th8;
end;

registration
  cluster non trivial for finite Group;
  existence by LmFiniteNontrivial;
end;


theorem Th9:
  for G being Group
  for H being Subgroup of G
  st H is trivial
  holds the multMagma of H = (1).G
proof
  let G be Group;
  let H be Subgroup of G;
  assume H is trivial;
  then the multMagma of H = (1).H by Th8
                         .= (1).G by GROUP_2:63;
  hence thesis;
end;


theorem Th10:
  for G being Group
  for H being trivial Subgroup of G
  for K being trivial Subgroup of G
  holds the multMagma of H = the multMagma of K
proof
  let G be Group;
  let H be trivial Subgroup of G;
  let K be trivial Subgroup of G;
  the multMagma of H = (1).G by Th9
                    .= the multMagma of K by Th9;
  hence thesis;
end;

theorem Th11:
  for G being Group
  for K being trivial Subgroup of G
  for H being Subgroup of G
  st H is Subgroup of K
  holds H is trivial Subgroup of G
proof
  let G be Group;
  let K be trivial Subgroup of G;
  let H be Subgroup of G;
  assume A1: H is Subgroup of K;
  the carrier of H = {1_G}
  proof
    the multMagma of K = (1).G by Th9;
    then the carrier of K = {1_G} by GROUP_2:def 7;
    then B1: the carrier of H c= {1_G} by A1,GROUP_2:def 5;
    (1).G is Subgroup of H by GROUP_2:65;
    then the carrier of (1).G c= the carrier of H by GROUP_2:def 5;
    then {1_G} c= the carrier of H by GROUP_2:def 7;
    hence the carrier of H = {1_G} by B1,XBOOLE_0:def 10;
  end;
  then ex x being object st the carrier of H = {x};
  hence H is trivial Subgroup of G;
end;

begin :: Proper Subgroups
definition
  let G be Group;
  let IT be Subgroup of G;
  attr IT is proper means
  :Def1:
  the multMagma of IT <> the multMagma of G;
end;
reserve G for Group;
reserve H for Subgroup of G;

theorem Th12:
  H is proper iff the carrier of H <> the carrier of G
proof
  (the carrier of H c= the carrier of G) & (the multF of H =
  (the multF of G)||(the carrier of H)) by GROUP_2:def 5;
  hence thesis;
end;

reserve h,x,y for object;

theorem Th13:
  H is proper iff (the carrier of G) \ (the carrier of H) is non empty set
proof
  set UG = the carrier of G;
  set UH = the carrier of H;
  thus H is proper implies (the carrier of G) \ (the carrier of H) is non empty set
  proof
    assume A1: H is proper;
    UH c= UG & UH <> UG by A1,Th12, GROUP_2:def 5;
    then (for x holds x in UH implies x in UG) &
    the carrier of H <> the carrier of G;
    then (for x holds x in UH implies x in UG) &
    not (for x holds x in UH iff x in UG) by TARSKI:2;
    hence (the carrier of G) \ (the carrier of H) is non empty set
    by XBOOLE_0:def 5;
  end;
  thus (the carrier of G) \ (the carrier of H) is non empty set implies H is proper
  proof
    assume A1: (the carrier of G) \ (the carrier of H) is non empty set;
    set GH = UG \ UH;
    not (GH is empty) by A1;
    then ex x st x in GH by XBOOLE_0:def 1;
    then consider y such that
    A2: y in GH;
    y in UG & not y in UH by A2, XBOOLE_0:def 5;
    then UG <> UH;
    then the multMagma of G <> the multMagma of H;
    hence H is proper;
  end;
  thus thesis;
end;

registration
  let G be non trivial Group;
  cluster proper for Subgroup of G;
  existence
  proof
    take (1).G;
    thus (1).G is proper;
  end;
end;

reserve G for non trivial Group;
reserve H for Subgroup of G;
registration
  let G be non trivial Group;
  cluster proper for Subgroup of G;
  existence
  proof
    take (1).G;
    thus (1).G is proper;
  end;
end;
reserve G for non trivial Group;
reserve H for Subgroup of G;

registration
  let G be non trivial Group;
  let H be non trivial Subgroup of G;
  cluster proper for Subgroup of H;
  existence
  proof
    take (1).H;
    thus (1).H is proper;
  end;
end;

Lm1:
  for G being Group
  for H being Subgroup of G
  st H is maximal
  holds H is proper by GROUP_4:def 6;

registration
  let G be non trivial Group;
  cluster maximal -> proper for Subgroup of G;
  coherence by Lm1;
end;

theorem Th14:
  for G being non trivial Group
  for H being proper Subgroup of G
  for K being Subgroup of G
  st H is Subgroup of K & the multMagma of H <> the multMagma of K
  holds K is non trivial Subgroup of G
proof
  let G be non trivial Group;
  let H be proper Subgroup of G;
  let K be Subgroup of G;
  assume A1: H is Subgroup of K;
  assume A2: the multMagma of H <> the multMagma of K;
  not (K is non trivial Subgroup of G) implies contradiction
  proof
    assume B1: not K is non trivial Subgroup of G;
    then K is trivial Subgroup of G;
    then H is trivial Subgroup of G by A1,Th11;
    then the multMagma of H = the multMagma of K by B1,Th10;
    hence contradiction by A2;
  end;
  hence K is non trivial Subgroup of G;
end;

begin :: Automorphisms
reserve G for Group;
reserve H for Subgroup of G;

definition :: Def2
  let G;
  mode Endomorphism of G is Homomorphism of G,G;
end;

reserve f for Endomorphism of G;
registration
  let G;
  cluster bijective for Endomorphism of G;
  existence
  proof
    reconsider i = id the carrier of G as Homomorphism of G,G by GROUP_6:38;
    i is bijective;
    hence thesis;
  end;
end;

definition :: Def3
  let G;
  mode Automorphism of G is bijective Endomorphism of G;
end;
reserve phi for Automorphism of G;

theorem Th15:
  Image (f|(1).G) = (1).G
proof
  Image(f|(1).G) = f .: ((1).G) by GRSOLV_1:def 3
                .= (1).G by GRSOLV_1:11;
  hence thesis;
end;

:: In particular, the trivial proper subgroup (1).G of G is invariant
:: under inner automorphisms, and thus is a characteristic subgroup.
theorem Th16:
  Image(phi|(1).G) is Subgroup of (1).G
proof
  (1).G is Subgroup of (1).G by GROUP_2:54;
  hence Image(phi|(1).G) is Subgroup of (1).G by Th15;
end;

theorem Th23:
  for G1,G2 being Group
  for f being Homomorphism of G1,G2
  for H being Subgroup of G1
  holds Ker(f|H) is Subgroup of Ker(f)
proof
  let G1,G2 be Group;
  let f be Homomorphism of G1,G2;
  let H be Subgroup of G1;
  A1: Ker(f|H) is Subgroup of G1 by GROUP_2:56;
  for g being Element of G1
  st g in Ker(f|H)
  holds g in Ker(f)
  proof
    let g be Element of G1;
    assume A2: g in Ker(f|H);
    Ker(f|H) is Subgroup of H;
    then A3: g in H by A2, LmSubgroupEltTrans;
    then A4: (f|H).g = f.g by Th2;
    g is Element of H by A3;
    then 1_G2 = f.g by A2,A4,GROUP_6:41;
    hence g in Ker(f) by GROUP_6:41;
  end;
  then Ker(f|H) is Subgroup of Ker(f) by A1,GROUP_2:58;
  hence thesis;
end;

Lm2: H is Subgroup of (1).G implies the multMagma of H = the multMagma of (1).G
proof
  assume H is Subgroup of (1).G;
  then H is Subgroup of (1).G & (1).G is Subgroup of H by GROUP_2:65;
  hence thesis by GROUP_2:55;
end;
Lm3:
(phi|H) is Homomorphism of H,Image(phi|H) & (phi|H) is one-to-one
proof
  thus phi|H is Homomorphism of H,Image(phi|H) by GROUP_6:49;
  Ker(phi) = (1).G by GROUP_6:56;
  then Ker(phi|H) is Subgroup of (1).G by Th23;
  then Ker(phi|H) = (1).G by Lm2
                 .= (1).H by GROUP_2:63;
  hence (phi|H) is one-to-one by GROUP_6:56;
end;

theorem Th17:
  (for f being Automorphism of G holds Image(f|H) is Subgroup of H) implies
  ex psi being Automorphism of G
  st psi = phi" & Image(phi|Image(psi|H)) is Subgroup of Image(phi|H)
proof
  assume A1: for f being Automorphism of G holds Image(f|H) is Subgroup of H;
  reconsider psi = phi" as Automorphism of G by GROUP_6:62;
  take psi;
  thus psi = phi";
  Image(psi|H) is Subgroup of H by A1;
  then phi .: Image(psi|H) is Subgroup of phi .: H by GRSOLV_1:12;
  then Image(phi|Image(psi|H)) is Subgroup of phi .: H by GRSOLV_1:def 3;
  hence Image(phi|Image(psi|H)) is Subgroup of Image(phi|H) by GRSOLV_1:def 3;
end;

theorem Th18:
  ex psi being Automorphism of G
  st psi = phi" & the multMagma of Image(phi|Image(psi|H)) = the multMagma of H
proof
  reconsider psi = phi" as Automorphism of G by GROUP_6:62;
  take psi;
  thus psi = phi";
  for g being Element of G holds g in Image(phi|Image(psi|H)) iff g in H
  proof
    let g be Element of G;
    thus g in Image(phi|Image(psi|H)) implies g in H
    proof
      assume g in Image(phi|Image(psi|H));
      then consider a being Element of Image(psi|H) such that
      B1: g = (phi|Image(psi|H)).a by GROUP_6:45;
      M1: a in Image(psi|H) & a is Element of G by GROUP_2:42;
      then B2: phi.a = g by B1, Th2;
      consider b being Element of H such that
      B3: a = (psi|H).b
      by M1,GROUP_6:45;
      M2: b in H & b is Element of G by GROUP_2:42;
      then b = phi.(psi.b) by Th6
            .= phi.((psi|H).b) by M2,Th2
            .= phi.a by B3
            .= g by B2;
      hence g in H;
    end;

    thus g in H implies g in Image(phi|Image(psi|H))
    proof
      assume B1: g in H;
      set a = (psi|H).g;
      B2: a in Image(psi|H)
      proof
        dom(psi|H) = the carrier of H by FUNCT_2:def 1;
        then g in dom(psi|H) by B1;
        then (psi|H).g in (psi|H) .: (the carrier of H) by FUNCT_1:def 6;
        then (psi|H).g in the carrier of Image(psi|H) by GROUP_6:def 10;
        then (psi|H).g in Image(psi|H);
        hence a in Image(psi|H);
      end;

      set K = Image(psi|H);
      set b = (phi|Image(psi|H)).a;

      B3: b in Image(phi|Image(psi|H))
      proof
        dom(phi|K) = the carrier of K by FUNCT_2:def 1;
        then a in dom(phi|K) by B2;
        then (phi|K).a in (phi|K) .: (the carrier of K) by FUNCT_1:def 6;
        then (phi|K).a in the carrier of Image(phi|K) by GROUP_6:def 10;
        then (phi|K).a in Image(phi|K);
        hence b in Image(phi|K);
      end;
      thus g in Image(phi|K)
      proof
        H is Subgroup of G & g in H & g is Element of G by B1;
        then B4: psi.g = (psi|H).g by Th2
                      .= a;
        B5: a is Element of K & K is Subgroup of G & a in K & phi is
        Homomorphism of G,G by B2;
        then a is Element of G by GROUP_2:42;
        then B6: (phi|K).a =  phi.a  by B5,Th2
                          .= phi.(psi.g) by B4
                          .= phi.((phi").g)
                          .= g by Th6;
        b = (phi|K).((psi|H).g)
         .= g by B6;
        hence thesis by B3;
      end;
    end;
    thus thesis;
  end;
  hence the multMagma of Image(phi|Image(psi|H)) = the multMagma of H by GROUP_2:60;
end;

theorem Th19:
  for H being strict Subgroup of G
  for K being Subgroup of G
  st Image(phi|H) is Subgroup of K
  holds ex psi being Automorphism of G
  st psi = phi" & H is Subgroup of Image(psi|K)
proof
  let H be strict Subgroup of G;
  let K be Subgroup of G;
  assume A1: Image(phi|H) is Subgroup of K;
  reconsider psi = phi" as Automorphism of G by GROUP_6:62;
  take psi;
  thus psi = phi";
  A2: psi" = phi by Th5;
  consider phi0 being Automorphism of G such that
  A3: phi0 = psi" and
  A4: the multMagma of Image(psi|Image(phi0|H)) = the multMagma of H
  by Th18;
  phi = phi0 by A2,A3;
  then A5: Image(psi|Image(phi|H)) = H by A4;
  psi .: Image(phi|H) is Subgroup of psi .: K by A1,GRSOLV_1:12;
  then Image(psi|Image(phi|H)) is Subgroup of psi .: K by GRSOLV_1:def 3;
  then Image(psi|Image(phi|H)) is Subgroup of Image(psi|K) by GRSOLV_1:def 3;
  hence H is Subgroup of Image(psi|K) by A5;
end;

theorem Th20:
  H,phi .: H are_isomorphic
proof
  reconsider H2 = phi .: H as Subgroup of G;
  phi|H is one-to-one by Lm3;
  then H,Image(phi|H) are_isomorphic by GROUP_6:68;
  hence H,phi .: H are_isomorphic by GRSOLV_1:def 3;
end;

theorem Th21:
  for G being finite Group
  for H1,H2 being strict Subgroup of G
  st H1,H2 are_isomorphic
  holds index H1 = index H2
proof
  let G be finite Group;
  let H1,H2 be strict Subgroup of G;
  assume H1,H2 are_isomorphic;
  then A1: card H1 = card H2 by GROUP_6:73;
  card H1 * index H1 = card G by GROUP_2:147
                    .= card H2 * index H2 by GROUP_2:147;
  then index H1 * card H1 = index H2 * card H1 by A1;
  hence index H1 = index H2 by XCMPLX_1:5;
end;

theorem Th22:
  G is finite implies
  for p being prime Nat
  for P being strict Subgroup of G
  st P is_Sylow_p-subgroup_of_prime p
  holds Image(phi|P) is_Sylow_p-subgroup_of_prime p
proof
  assume A0: G is finite;
  let p be prime Nat;
  let P be strict Subgroup of G;
  assume A1: P is_Sylow_p-subgroup_of_prime p;
  then A2: P is p-group by GROUP_10:def 18;
  set Q = (phi .: P);
  A3: P,Q are_isomorphic by Th20;
  then A4: card P = card Q by GROUP_6:75;
  consider r being Nat such that
  A5: card P = p |^ r
  by A2,GROUP_10:def 17;
  card Q = p |^ r by A4,A5;
  then A6: Q is p-group by GROUP_10:def 17;
  A7: index P = index Q by A0,A3,Th21;
  A8: Q = Image(phi|P) by GRSOLV_1:def 3;
  not p divides index P by A1, GROUP_10:def 18;
  then not p divides index Q by A7;
  hence Image(phi|P) is_Sylow_p-subgroup_of_prime p by A6, A8, GROUP_10:def 18;
end;

theorem Th24:
  for f being Automorphism of G
  st Image(f|H) = H
  holds f|H is Automorphism of H
proof
  let f be Automorphism of G;
  assume A1: Image(f|H) = H;
  then C1: f|H is Homomorphism of H,H by GROUP_6:49;
  C2: f|H is one-to-one by Lm3;

  f|H is onto Endomorphism of H
  proof
    set UH = the carrier of H;
    f|H is Function of UH,UH & rng(f|H) = the carrier of H by C1, GROUP_6:44, A1;
    then f|H is onto Function of UH,UH by FUNCT_2:def 3;
    then f|H is onto Homomorphism of H,H by C1;
    hence thesis;
  end;
  then f|H is bijective Homomorphism of H,H by C2;
  then f|H is Automorphism of H;
  hence thesis;
end;

theorem Th25:
  for G being non trivial Group
  for H being Subgroup of G
  for phi being Automorphism of G
  st H is proper Subgroup of G
  holds Image(phi|H) is proper Subgroup of G
proof
  let G be non trivial Group;
  let H be Subgroup of G;
  let phi be Automorphism of G;
  set UH = the carrier of H;
  set UG = the carrier of G;
  A1: phi is one-to-one & phi is onto & UH is non empty Subset of UG &
      phi is Function of UG,UG by GROUP_2:def 5;
  assume H is proper Subgroup of G;
  then UG \ UH is non empty by Th13;
  then consider x such that
  A2: x in UG \ UH by XBOOLE_0:def 1;
  A3: x in G & not x in H by A2,XBOOLE_0:def 5;
  A4: not (phi.x in phi .: H)
      proof
        not (phi.x in (phi .: UH)) by A1, A3, Th7;
        hence not (phi.x in (phi .: H)) by GRSOLV_1:8;
      end;
  phi.x is Element of G
  proof
    dom phi = UG & rng phi = UG by A1, FUNCT_2:def 1;
    then phi.x in UG by A3, FUNCT_1:def 3;
    hence phi.x is Element of G;
  end;
  then ex y being Element of G st not y in phi .: H by A4;
  then phi .: H is proper;
  hence Image(phi|H) is proper Subgroup of G by GRSOLV_1:def 3;
end;

theorem Th26:
  for G being non trivial Group
  for H being strict Subgroup of G
  for phi being Automorphism of G
  st H is maximal
  holds Image(phi|H) is maximal
proof
  let G be non trivial Group;
  let H be strict Subgroup of G;
  let phi be Automorphism of G;
  assume A1: H is maximal;
  A2: Image(phi|H) is proper Subgroup of G by A1,Th25;
  then P1: the multMagma of Image(phi|H) <> the multMagma of G by Def1;
  set UG = the carrier of G;
  set UH = the carrier of H;
  P2: for K being strict Subgroup of G
  st Image(phi|H) <> K & Image(phi|H) is Subgroup of K
  holds K = the multMagma of G
  proof
    let K be strict Subgroup of G;
    assume B1: Image(phi|H) <> K;
    assume B2: Image(phi|H) is Subgroup of K;
    then consider psi being Automorphism of G such that
    B3: psi = phi" and
    B4: H is Subgroup of Image(psi|K)
    by Th19;
    set UK = the carrier of K;
    reconsider K as non trivial strict Subgroup of G by A2,B1,B2,Th14;
    UK \ (the carrier of Image(phi|H)) is non empty by B1,B2,Def1,Th13;
    then consider k being object such that
    B6: k in UK \ (the carrier of Image(phi|H))
    by XBOOLE_0:def 1;
    reconsider k as Element of K by B6;
    set L = Image(psi|K);
    B8: psi.k in L
    proof
      C1: k in G by GROUP_2:41;
      consider l being object such that
      C2: l = psi.k;
      dom psi = the carrier of G by FUNCT_2:def 1;
      then l in psi .: (the carrier of K) by C1,C2,FUNCT_1:def 6;
      then l in the carrier of (psi .: K) by GRSOLV_1:8;
      hence psi.k in Image(psi|K) by C2,GRSOLV_1:def 3;
    end;
    B9: the multMagma of H <> L
    proof
      set UPH = the carrier of Image(phi|H);
      C1: phi is one-to-one & phi is onto & UPH is non empty Subset of UG &
      phi is Function of UG,UG by GROUP_2:def 5;
      k in G & not k in Image(phi|H) by B6, XBOOLE_0:def 5, GROUP_2:41;
      then C2: not psi.k in (psi .: UPH) by C1,Th7;
      consider phi2 being Automorphism of G such that
      C3: phi2 = psi" and
      C4: the multMagma of Image(psi|Image(phi2|H)) = the multMagma of H
      by Th18;
      phi2=phi by C3,B3, Th5;
      then C5: the multMagma of Image(psi|Image(phi|H)) = the multMagma of H by C4;
      set UPH = the carrier of Image(phi|H);
      psi .: UPH = the carrier of (psi .: Image(phi|H)) by GRSOLV_1:8
                .= the carrier of Image(psi|Image(phi|H)) by GRSOLV_1:def 3;
      then the carrier of H <> the carrier of L by B8,C2,C5;
      hence thesis;
    end;
    B10: Image(phi|L) = the multMagma of G
    proof
      L = the multMagma of G by A1,B4,B9,GROUP_4:def 6;
      then phi is Function of UG,UG & phi is onto & the carrier of L = UG;
      then phi .: the carrier of L = phi .: UG
                                  .= rng phi by RELSET_1:22
                                  .= UG by FUNCT_2:def 3;
      then UG = phi .: (the carrier of L)
             .= the carrier of (phi .: L) by GRSOLV_1:8
             .= the carrier of Image(phi|L) by GRSOLV_1:def 3;
      then the carrier of Image(phi|L) = the carrier of G;
      then the multMagma of Image(phi|L) = the multMagma of G by GROUP_2:61;
      hence thesis;
    end;
    Image(phi|L) = K
    proof
      consider psi2 being Automorphism of G such that
      C1: psi2 = phi" and
      C2: the multMagma of Image(phi|Image(psi2|K)) = the multMagma of K
      by Th18;
      thus Image(phi|Image(psi|K)) = K by B3,C1,C2;
    end;
    hence thesis by B10;
  end;
  thus Image(phi|H) is maximal by P1,P2,GROUP_4:def 6;
end;

begin :: Inner Automorphisms
definition :: Def4
  let G;
  let IT be Automorphism of G;
  attr IT is inner means
  :Def4:
  ex a being Element of G st
  for x being Element of G holds IT.x = x |^ a;
end;
notation
  let G be Group, f be Automorphism of G;
  antonym f is outer for f is inner;
end;

theorem Th27:
  for x being Element of G holds (id the carrier of G).x = x |^ 1_G by GROUP_3:19;

registration
  let G;
  cluster inner for Automorphism of G;
  existence
  proof
    reconsider i = id (the carrier of G) as Automorphism of G by GROUP_6:38;
    take i;
    take 1_G;
    thus thesis by Th27;
  end;
end;

theorem Th28:
  for G being strict Group, f being object
  holds (f in Aut G) iff (f is Automorphism of G)
proof
  let G be strict Group;
  let f be object;
  thus f in Aut G implies f is Automorphism of G
  proof
    assume A1: f in Aut G;
    then reconsider f as Endomorphism of G by AUTGROUP:def 1;
    f is bijective by A1,AUTGROUP:def 1;
    hence thesis;
  end;
  thus f is Automorphism of G implies f in Aut G by AUTGROUP:def 1;
  thus thesis;
end;

Lm6:
  for G being strict Group
  for f being Element of InnAut G
  holds f is Automorphism of G
proof
  let G be strict Group;
  let f be Element of InnAut G;
  f is Element of Aut G by AUTGROUP:12;
  hence f is Automorphism of G by Th28;
end;

theorem Th29:
  for G being strict Group
  for f being object
  holds (f in InnAut G) iff (f is inner Automorphism of G)
proof
  let G be strict Group;
  let f be object;
  A1: f is Automorphism of G implies
      f is Element of Funcs (the carrier of G, the carrier of G) by FUNCT_2:9;
  thus (f in InnAut G) implies (f is inner Automorphism of G)
  proof
    assume B1: f in InnAut G;
    then reconsider f as Automorphism of G by Lm6;
    consider a being Element of G such that
    B2: for x being Element of G holds f.x = x |^ a
    by A1,B1,AUTGROUP:def 4;
    thus thesis by Def4,B2;
  end;
  thus (f is inner Automorphism of G) implies (f in InnAut G)
  proof
    assume f is inner Automorphism of G;
    then reconsider f as inner Automorphism of G;
    consider a being Element of G such that
    B1: for x being Element of G holds f.x = x |^ a
    by Def4;
    thus thesis by A1,B1,AUTGROUP:def 4;
  end;
  thus thesis;
end;

theorem Th30:
  for a being Element of G
  for f being inner Automorphism of G
  st (for x being Element of G holds f.x = x |^ a)
  holds Image(f|H) = H |^ a
proof
  let a be Element of G,
      f be inner Automorphism of G;
  assume
A1: for x being Element of G holds f.x = x |^ a;
C1: for h being Element of G st h in H holds (f|H).h = h |^ a
  proof
    let h be Element of G;
    assume h in H;
    hence (f|H).h = f.h by Th2
                 .= h |^ a by A1;
  end;

C2: for y being Element of G st y in Image(f|H) holds y in H |^ a
  proof
    let y be Element of G;
    assume y in Image(f|H);
    then consider h being Element of H such that
    B1: (f|H).h = y by GROUP_6:45;
    reconsider h as Element of G by GROUP_2:42;
    B2: h in H;
    then h |^ a = (f|H).h by C1
               .= y by B1;
    hence y in H |^ a by B2,GROUP_3:58;
  end;
C3: for y being Element of G st y in H |^ a holds y in Image(f|H)
  proof
    let y be Element of G;
    assume y in H |^ a;
    then consider g being Element of G such that
    B1:    y=g|^a and
    B2:    g in H
    by GROUP_3:58;

    B3: (f|H).g = f.g by Th2,B2
               .= g |^ a by A1
               .= y by B1;
    thus y in Image(f|H) by B2,B3,GROUP_6:45;
  end;
  thus (H |^ a) = Image(f|H) by C2,C3;
end;

theorem Th31:
  for a being Element of G
  for f being Endomorphism of G
  st (for x being Element of G holds f.x = x |^ a)
  holds Ker f = (1).G
proof
  let a be Element of G;
  let f be Endomorphism of G;
  assume A1: for x being Element of G holds f.x = x |^ a;
  for x being Element of G holds x in Ker f implies x in (1).G
  proof
    let x be Element of G;
    assume x in Ker f;
    then 1_G = f.x by GROUP_6:41
            .= x |^ a by A1;
    then x = 1_G by GROUP_3:18;
    hence x in (1).G by GROUP_2:46;
  end;
  then A2: Ker f is Subgroup of (1).G by GROUP_2:58;

  A3: (1).G is Subgroup of Ker f by GROUP_2:65;
  thus Ker f = (1).G by A2,A3,GROUP_2:55;
end;

theorem Th32:
  for a being Element of G
  for f being Endomorphism of G
  st (for x being Element of G holds f.x = x |^ a)
  holds f is Automorphism of G
proof
  let a be Element of G;
  let f be Endomorphism of G;
  assume A1: for x being Element of G holds f.x = x |^ a;
  then Ker f = (1).G by Th31;
  then A2: f is one-to-one by GROUP_6:56;
  ex fInv being Endomorphism of G st f*fInv = id (the carrier of G)
  proof
    deffunc F(Element of G) = ($1) |^ a";
    consider fInv be Function of the carrier of G, the carrier of G such that
    A3: for g being Element of G holds fInv.g = F(g) from FUNCT_2:sch 4;
    for x1,x2 being Element of G holds fInv.(x1 * x2) = fInv.x1 * fInv.x2
    proof
      let x1,x2 be Element of G;
      A4: fInv.x1 = x1 |^ a" & fInv.x2 = x2 |^ a" by A3;
      fInv.(x1 * x2) = (x1 * x2) |^ a" by A3
                    .= (x1 |^ a") * (x2 |^ a") by GROUP_3:23
                    .= fInv.x1 * fInv.x2 by A4;
      hence thesis;
    end;
    then reconsider fInv as Endomorphism of G by GROUP_6:def 6;
    for x being Element of G holds (f*fInv).x = (id the carrier of G).x
    proof
      let x be Element of G;
      (f * fInv).x = f.(fInv.x) by FUNCT_2:15
                  .= f.(x |^ a") by A3
                  .= (x |^ a") |^ a by A1
                  .= x |^ (a" * a) by GROUP_3:24
                  .= x |^ 1_G by GROUP_1:def 5
                  .= x by GROUP_3:19
                  .= (id the carrier of G).x;
      hence thesis;
    end;
    then f*fInv = id the carrier of G;
    hence thesis;
  end;

  then f is onto by FUNCT_2:18;
  hence f is Automorphism of G by A2;
end;

theorem Th33:
  for a being Element of G
  for f being Endomorphism of G
  st (for x being Element of G holds f.x = x |^ a)
  holds f is inner Automorphism of G by Th32,Def4;

theorem Th34:
  for a being Element of G
  holds ex f being inner Automorphism of G st (for x being Element of G
  holds f.x = x |^ a)
proof
  let a be Element of G;
  deffunc F(Element of G) = ($1) |^ a;
  consider f be Function of the carrier of G, the carrier of G such that
A1: for g being Element of G holds f.g = F(g) from FUNCT_2:sch 4;
  for x1,x2 being Element of G holds f.(x1 * x2) = f.x1 * f.x2
  proof
    let x1,x2 be Element of G;
    A2: f.x1 = x1 |^ a & f.x2 = x2 |^ a by A1;
    f.(x1 * x2) = (x1 * x2) |^ a by A1
               .= (x1 |^ a) * (x2 |^ a) by GROUP_3:23
               .= f.x1 * f.x2 by A2;
    hence thesis;
  end;
  then reconsider f as Endomorphism of G by GROUP_6:def 6;
  for x being Element of G holds f.x = x |^ a & f is inner Automorphism of G
  by A1,Th33;
  hence thesis;
end;

theorem Th35:
  for H being strict Subgroup of G
  holds (H is normal) iff (for f being inner Automorphism of G holds Image(f|H)=H)
proof
  let H be strict Subgroup of G;
  A1: (H is normal) implies (for f being inner Automorphism of G holds Image(f|H)=H)
  proof
    assume B1: H is normal;
    let f be inner Automorphism of G;
    consider a being Element of G such that
    B2: for x being Element of G holds f.x = x |^ a
    by Def4;
    Image(f|H) = H |^ a by B2,Th30
              .= the multMagma of H by B1,GROUP_3:def 13
              .= H;
    hence Image(f|H)=H;
  end;
  A2: not ((for f being inner Automorphism of G holds Image(f|H)=H) implies H is normal)
  implies contradiction
  proof
    assume B1: for f being inner Automorphism of G holds Image(f|H)=H;
    assume not H is normal;
    then consider a being Element of G such that
    B2: H |^ a <> the multMagma of H
    by GROUP_3:def 13;
    consider f being inner Automorphism of G such that
    B3: (for x being Element of G holds f.x= x |^ a)
    by Th34;
    Image(f|H) = H |^ a by B3, Th30;
    hence contradiction by B1,B2;
  end;
  thus thesis by A1,A2;
end;

begin :: Characteristic Subgroups
definition
  let G;
  let IT be Subgroup of G;
  attr IT is characteristic means
  :Def6:
  for f being Automorphism of G
  holds Image (f|IT) = IT;
end;

Lm8: H is Subgroup of (1).G implies the multMagma of H = the multMagma of (1).G
proof
  assume H is Subgroup of (1).G;
  then reconsider H as Subgroup of (1).G;
  H is Subgroup of (1).G & (1).G is Subgroup of H by GROUP_2:65;
  hence thesis by GROUP_2:55;
end;

Lm7: (1).G is characteristic
proof
  for f being Automorphism of G holds Image(f|(1).G) = (1).G
  proof
    let f be Automorphism of G;
    reconsider I = Image(f|(1).G) as Subgroup of (1).G by Th16;
    (1).G = I by Lm8;
    hence Image(f|(1).G) = (1).G;
  end;
  hence (1).G is characteristic;
end;


theorem Th36:
  ex H st H is characteristic
proof
  take H = (1).G;
  thus H is characteristic by Lm7;
end;

registration
  let G;
  cluster characteristic for Subgroup of G;
  existence by Th36;
end;
reserve K for characteristic Subgroup of G;
registration
  let G be Group;
  cluster strict characteristic for Subgroup of G;
  existence
  proof
    take (1).G;
    thus thesis by Lm7;
  end;
end;

theorem Th37:
  K is normal Subgroup of G
proof
A1:  for a being Element of G holds K |^ a = K
  proof
    let a be Element of G;
    consider f being inner Automorphism of G such that
  A2: for x being Element of G holds f.x = x |^ a
    by Th34;
    K = Image(f|K) by Def6
     .= K |^ a by A2,Th30;
    hence thesis;
  end;
  for a being Element of G holds the carrier of K |^ a = the carrier of K by A1;
  then for a being Element of G holds the multMagma of K = K |^ a by GROUP_2:59;
  hence K is normal Subgroup of G by GROUP_3:def 13;
end;

registration
  let G be Group;
  cluster characteristic -> normal for Subgroup of G;
  coherence by Th37;
end;

theorem Th38:
  for H being strict Subgroup of G
  st (for K being strict Subgroup of G
      st card K = card H
      holds H = K)
  holds H is characteristic
proof
  let H be strict Subgroup of G;
  assume A1: for K being strict Subgroup of G st card K = card H holds H = K;
  H is characteristic
  proof
    let phi be Automorphism of G;
    Image(phi|H) = phi .: H by GRSOLV_1:def 3;
    then card H = card Image(phi|H) by Th20,GROUP_6:73;
    hence Image(phi|H) = H by A1;
  end;
  hence thesis;
end;

theorem Th40:
  for G1,G2 being Group
  for H1 being Subgroup of G1
  for K being Subgroup of H1
  for H2 being Subgroup of G2
  for f being Homomorphism of G1,G2
  for g being Homomorphism of H1,H2
  st (for k being Element of G1 st k in K holds f.k=g.k)
  holds Image(f|K) = Image(g|K)
proof
  let G1,G2 be Group;
  let H1 be Subgroup of G1;
  let K be Subgroup of H1;
  let H2 be Subgroup of G2;
  let f be Homomorphism of G1,G2;
  let g be Homomorphism of H1,H2;
  assume A1: for k being Element of G1 st k in K holds f.k=g.k;
  A2: Image(f|K) is strict Subgroup of G2 &
      Image(g|K) is strict Subgroup of G2 by GROUP_2:56;
  for y being object
  holds y in the carrier of Image(f|K) iff y in the carrier of Image(g|K)
  proof
    let y be object;
    thus y in the carrier of Image(f|K) implies y in the carrier of Image(g|K)
    proof
      assume y in the carrier of Image(f|K);
      then consider h being Element of K such that
      B1: (f|K).h = y
      by STRUCT_0:def 5,GROUP_6:45;
      B2: h is Element of G1 & h is Element of H1 & h in K by GROUP_2:42;
      f.h = g.h by A1,B2
         .= (g|K).h by B2, Th2;
      then (g|K).h = f.h
                  .= (f|K).h by B2,Th2
                  .= y by B1;
      hence y in the carrier of Image(g|K) by STRUCT_0:def 5,GROUP_6:45;
    end;
    thus y in the carrier of Image(g|K) implies y in the carrier of Image(f|K)
    proof
      assume y in the carrier of Image(g|K);
      then consider h being Element of K such that
      C1: (g|K).h = y
      by STRUCT_0:def 5,GROUP_6:45;
      C2: h is Element of H1 & h is Element of G1 & h in K by GROUP_2:42;
      g.h = f.h by A1,C2
         .= (f|K).h by C2,Th2;
      then (f|K).h = g.h
                  .= (g|K).h by C2,Th2
                  .= y by C1;
      hence y in the carrier of Image(f|K) by STRUCT_0:def 5,GROUP_6:45;
    end;
    thus thesis;
  end;
  hence Image(f|K) = Image(g|K) by A2,GROUP_2:59,TARSKI:2;
end;

theorem Th39:
  for N being strict normal Subgroup of G
  for K being characteristic Subgroup of N
  holds K is normal Subgroup of G
proof
  let N be strict normal Subgroup of G;
  let K be characteristic Subgroup of N;
  for a being Element of G holds K |^ a = K
  proof
    let a be Element of G;
    consider g being inner Automorphism of G such that
    A1: for x being Element of G holds g.x = x |^ a
    by Th34;

    Image(g|N) = N by Th35;
    then reconsider f = g|N as Automorphism of N by Th24;
    A2: Image(f|K) = K by Def6;

    for k being Element of G st k in K holds f.k = g.k by Th2,GROUP_2:40;
    then Image(f|K) = Image(g|K) by Th40;
    then Image(g|K) = K & Image(g|K) = K |^ a by A1,A2,Th30;
    then K = K |^ a;
    hence thesis;
  end;
  hence K is normal Subgroup of G by Th4;
end;

theorem Th41:
  for N being characteristic Subgroup of G
  for K being characteristic Subgroup of N
  holds K is characteristic Subgroup of G
proof
  let N be characteristic Subgroup of G;
  let K be characteristic Subgroup of N;
  for g being Automorphism of G holds Image(g|K) = K
  proof
    let g be Automorphism of G;
    Image(g|N) = N by Def6;
    then reconsider f = g|N as Automorphism of N by Th24;
    A1: Image(f|K) = K by Def6;

    for k being Element of G st k in K holds f.k = g.k by Th2, GROUP_2:40;
    then Image(g|K) = Image(f|K) by Th40
                   .= K by A1;
    hence Image(g|K) = K;
  end;
  hence K is characteristic Subgroup of G by Def6;
end;

theorem Th42:
  for H being strict Subgroup of G
  holds H is characteristic Subgroup of G iff
  (for phi holds Image(phi|H) is Subgroup of H)
proof
  let H be strict Subgroup of G;
  thus H is characteristic Subgroup of G implies
       (for phi holds Image(phi|H) is Subgroup of H)
  proof
    assume H is characteristic Subgroup of G;
    then Image(phi|H) = H & H is Subgroup of H by GROUP_2:54,Def6;
    hence Image(phi|H) is Subgroup of H;
  end;

  thus (for phi holds Image(phi|H) is Subgroup of H)
       implies H is characteristic Subgroup of G
  proof
    assume A1: Image(phi|H) is Subgroup of H;
    A2: H is Subgroup of Image(phi|H)
    proof
      consider psi being Automorphism of G such that
      B1: psi = phi" and
      B2: Image(phi|Image(psi|H)) is Subgroup of Image(phi|H) by A1,Th17;
      consider psi2 being Automorphism of G such that
      B3: psi2 = phi" and
      B4: the multMagma of H = the multMagma of Image(phi|Image(psi2|H)) by Th18;
      thus H is Subgroup of Image(phi|H) by B1,B2,B3,B4;
    end;
    H = Image(phi|H)
    proof
      H is Subgroup of Image(phi|H) & Image(phi|H) is Subgroup of H
      by A1,A2;
      hence H = Image(phi|H) by GROUP_2:55;
    end;
    hence H is characteristic Subgroup of G by Def6;
  end;

  thus thesis;
end;


theorem Th43:
  center G is characteristic Subgroup of G
proof
  set Z = center G;
  A1: for y,z being Element of G
  st z in Z
  holds (phi.z)*y = y*phi.z
  proof
    let y,z be Element of G;
    assume B1: z in Z;
    set x = (phi").y;
    (phi.z)*y = (phi.z)*(phi.x) by Th6
             .= phi.(z*x) by GROUP_6:def 6
             .= phi.(x*z) by B1,GROUP_5:77
             .= (phi.x)*(phi.z) by GROUP_6:def 6
             .= y*(phi.z) by Th6;
    hence thesis;
  end;
  A2: for z being Element of G
  st z in Z
  holds (phi|Z).z in Z
  proof
    let z be Element of G;
    assume B1: z in Z;
    then for y being Element of G holds (phi.z)*y=y*(phi.z) by A1;
    then (phi.z) in Z by GROUP_5:77;
    hence ((phi|Z).z) in Z by B1,Th2;
  end;
  Image(phi|Z) is Subgroup of Z
  proof
    B1: the carrier of Z c= the carrier of G by GROUP_2:def 5;
    for w being Element of G st w in rng(phi|Z) holds w in Z
    proof
      let w be Element of G;
      assume w in rng(phi|Z);
      then consider z being object such that
      C1: z in dom(phi|Z) and
      C2: (phi|Z).z = w by FUNCT_1:def 3;
      reconsider z as Element of Z by C1;
      z is Element of G by GROUP_2:42;
      hence w in Z by C2,A2,STRUCT_0:def 5;
    end;
    then for w being Element of G st w in rng(phi|Z) holds w in the carrier of Z
    by STRUCT_0:def 5;
    then rng(phi|Z) c= the carrier of Z by B1,SUBSET_1:2;
    then the carrier of Image(phi|Z) c= the carrier of Z by GROUP_6:44;
    hence Image(phi|Z) is Subgroup of Z by GROUP_2:57;
  end;

  hence Z is characteristic Subgroup of G by Th42;
end;

reserve G for non trivial Group;
reserve H,K for Subgroup of G;
reserve A,A1,A2 for set;

scheme
  CharMeet{G() -> Group, P[set]} :
  for phi being Automorphism of G()
  holds phi .: meet{A where A is Subset of G() : ex K being strict Subgroup
  of G() st A = the carrier of K & P[K]} = meet{A where A is Subset of G() :
  ex K being strict Subgroup of G() st A = the carrier of K & P[K]}
provided
A1: for phi being Automorphism of G()
    for H being strict Subgroup of G()
    st P[H]
    holds P[Image(phi|H)] and
A2: ex H being strict Subgroup of G() st P[H]
proof
  let phi be Automorphism of G();
  set UG = the carrier of G();
  set Fam = {A where A is Subset of G() : ex K being strict Subgroup
  of G() st A = the carrier of K & P[K]};
  consider H being strict Subgroup of G() such that
A3: P[H]
  by A2;
  A4: Fam <> {}
  proof
    consider A such that
    B1: A = the carrier of H;
    the carrier of H is Subset of G() by GROUP_2:def 5;
    then A in Fam by A3, B1;
    hence thesis;
  end;

  A5: for phi0 being Automorphism of G()
  for x being object st x in meet Fam
  holds phi0.x in meet Fam
  proof
    let phi0 be Automorphism of G();
    let x be object;
    assume x in meet Fam;
    then B1: for A1 holds A1 in Fam implies x in A1 by SETFAM_1:def 1;
    for A holds A in Fam implies phi0.x in A
    proof
      let A;
      assume C1: A in Fam;
      consider A0 being Subset of G() such that
      C2: A0=A & ex H being strict Subgroup of G() st A0 = the carrier of H & P[H]
      by C1;
      consider K being strict Subgroup of G() such that
      C3: A = the carrier of K & P[K]
      by C2;
      consider psi being Automorphism of G() such that
      C4: psi = phi0" & the multMagma of Image(phi0|Image(psi|K)) = the multMagma of K
      by Th18;
      x in K by C1,B1,C3;
      then C5: x in G() & dom phi0 = the carrier of G() by GROUP_2:40,FUNCT_2:def 1;
      P[Image(psi|K)] by C3,A1;
      then carr Image(psi|K) in Fam;
      then x in carr Image(psi|K) by B1;
      then phi0.x in phi0 .: (carr Image(psi|K)) by C5, FUNCT_1:def 6;
      then phi0.x in carr (phi0 .: Image(psi|K)) by GRSOLV_1:8;
      hence phi0.x in A by C3,C4,GRSOLV_1:def 3;
    end;
    hence thesis by A4, SETFAM_1:def 1;
  end;

  for x being object st x in meet Fam
  holds x in phi .: meet Fam
  proof
    let x be object;
    assume B1: x in meet Fam;
    then carr H in Fam & for A1 holds A1 in Fam implies x in A1 by A3,SETFAM_1:def 1;
    then B2: x in H;
    then B3: x is Element of G() by GROUP_2:42;
    reconsider psi = phi" as Automorphism of G() by GROUP_6:62;
    B4: dom phi = the carrier of G() by FUNCT_2:def 1;
    B5: psi.x in meet Fam by B1,A5;
    B6: phi.(psi.x) = x by B3,Th6;
    psi is bijective & x in G() by B2, GROUP_2:40;
    then psi.x in dom phi by B4, FUNCT_2:5;
    hence x in phi .: meet Fam by B6,B5,FUNCT_1:def 6;
  end;
  then P1: meet Fam c= phi .: meet Fam by TARSKI:def 3;

  for y being object st y in phi .: meet Fam
  holds y in meet Fam
  proof
    let y be object;
    assume y in phi .: meet Fam;
    then consider x being object such that
    B1: x in dom phi & x in meet Fam & y = phi.x
    by FUNCT_1:def 6;
    thus y in meet Fam by B1,A5;
  end;
  then P2: phi .: meet Fam c= meet Fam by TARSKI:def 3;

  thus thesis by P1,P2,XBOOLE_0:def 10;

end;

scheme
  MeetIsChar{G() -> Group, P[set]} :
  ex K being strict Subgroup of G() st
  the carrier of K = meet {A where A is Subset of G() :
  ex H being strict Subgroup of G() st A = the carrier of H & P[H]} &
  K is characteristic
provided
A1: for phi being Automorphism of G()
    for H being strict Subgroup of G()
    st P[H]
    holds P[Image(phi|H)] and
A2: ex H being strict Subgroup of G() st P[H]
proof
  set Fam = {A where A is Subset of G() :
             ex H being strict Subgroup of G()
             st A = the carrier of H & P[H]};

  A3: for phi being Automorphism of G()
  holds phi .: meet Fam = meet Fam from CharMeet(A1,A2);

  consider K being strict Subgroup of G() such that
  A4: the carrier of K = meet Fam
  from GROUP_4:sch 1(A2);
  take K;

  for phi being Automorphism of G()
  holds Image(phi|K) = K
  proof
    let phi be Automorphism of G();
    the carrier of Image(phi|K)
     = the carrier of phi .: K by GRSOLV_1:def 3
    .= phi .: (the carrier of K) by GRSOLV_1:8
    .= phi .: meet Fam by A4
    .= meet Fam by A3
    .= the carrier of K by A4;
    hence Image(phi|K) = K by GROUP_2:59;
  end;
  hence thesis by A4;
end;

theorem Th44:
  (ex H being strict Subgroup of G st H is maximal) implies
  Phi(G) is characteristic Subgroup of G
proof
  defpred P[Subgroup of G] means $1 is maximal;
  assume A1: ex H being strict Subgroup of G st P[H];
  set MaxSubCarrs = {A where A is Subset of G :
                     ex H being strict Subgroup of G
                     st A = the carrier of H & P[H]};

  A2: for phi being Automorphism of G
  for H being strict Subgroup of G
  st P[H]
  holds P[Image(phi|H)] by Th26;

  consider K being strict Subgroup of G such that
  A3: the carrier of K = meet {A where A is Subset of G :
      ex H being strict Subgroup of G st A = the carrier of H & P[H]} and
  A4: K is characteristic
  from MeetIsChar(A2,A1);
  K = Phi(G) by A1,A3,GROUP_4:def 7;
  hence thesis by A4;
end;

definition
  let G be finite Group;
  let p be prime Nat;
  func p-core_of_G -> strict Subgroup of G means
  :Def7:
  the carrier of it = meet{A where A is Subset of G :
  ex P being strict Subgroup of G st A = the carrier of P &
  P is_Sylow_p-subgroup_of_prime p};
  existence
  proof
    defpred SPS[Subgroup of G] means $1 is_Sylow_p-subgroup_of_prime p;
    A1: ex P being strict Subgroup of G st SPS[P]
    by GROUP_10:10;
    ex H being strict Subgroup of G st the carrier of H = meet{A where
    A is Subset of G: ex P being strict Subgroup of G st A = the carrier of P & SPS[P]}
    from GROUP_4:sch 1(A1);
    hence thesis;
  end;
  uniqueness by GROUP_2:59;
  correctness;
end;

theorem Th45:
  for G being finite Group
  for p being prime Nat
  holds p-core_of_G is characteristic
proof
  let G be finite Group;
  let p be prime Nat;
  defpred P[Subgroup of G] means $1 is_Sylow_p-subgroup_of_prime p;

  A1: ex H being strict Subgroup of G st P[H] by GROUP_10:10;
  set MaxSubCarrs = {A where A is Subset of G :
                     ex H being strict Subgroup of G
                     st A = the carrier of H & P[H]};

  A2: for phi being Automorphism of G
  for P being strict Subgroup of G
  st P[P]
  holds P[Image(phi|P)] by Th22;

  consider K being strict Subgroup of G such that
  A4: the carrier of K = meet {A where A is Subset of G :
      ex H being strict Subgroup of G st A = the carrier of H & P[H]} and
  A5: K is characteristic
  from MeetIsChar(A2,A1);
  K = p-core_of_G by A4,Def7;
  hence thesis by A5;
end;

theorem Th46:
  for phi being Automorphism of G
  holds phi .: commutators G = commutators G
proof
  let phi be Automorphism of G;
  for g being object
  st g in commutators G
  holds g in phi .: commutators G
  proof
    let g be object;
    assume B1: g in commutators G;
    then reconsider g as Element of G;
    consider a,b being Element of G such that
    B2: g = [.a,b.]
    by B1, GROUP_5:58;
    reconsider psi = phi" as Automorphism of G by GROUP_6:62;
    set x = psi.a;
    set y = psi.b;
    set h = [.x,y.];
    dom phi = the carrier of G by FUNCT_2:def 1;
    then B3: h in dom phi;
    psi.g = psi.([.a,b.]) by B2
         .= [.psi.a,psi.b.] by GROUP_6:34
         .= h;
    then B4: psi.g = h;
    B5: phi.((phi").g) = g by Th6;
    h in dom phi & h in commutators G by B3;
    then phi.h in phi .: commutators G by FUNCT_1:def 6;
    then phi.(psi.g) in phi .: commutators G by B4;
    then phi.((phi").g) in phi .: commutators G;
    then g in phi .: commutators G by B5;
    hence thesis;
  end;
  then P1: commutators G c= phi .: commutators G by TARSKI:def 3;
  for h being object
  st h in phi .: commutators G
  holds h in commutators G
  proof
    let h be object;
    assume B1: h in phi .: commutators G;
    consider g being object such that
        g in dom phi and
    B2: g in commutators G and
    B3: h = phi.g
    by B1,FUNCT_1:def 6;
    consider a,b be Element of G such that
    B4: g = [.a,b.]
    by B2,GROUP_5:58;
    h = phi.g by B3
     .= phi.([.a,b.]) by B4
     .= [.phi.a, phi.b.] by GROUP_6:34;
    hence h in commutators G;
  end;
  then phi .: commutators G c= commutators G by TARSKI:def 3;
  hence commutators G = phi .: commutators G by P1,XBOOLE_0:def 10;
end;

theorem Th47:
  for phi being Automorphism of G
  for H being Subgroup of G
  st (for h being Element of H
      holds phi.h in H)
  holds Image(phi|H) is Subgroup of H
proof
  let phi be Automorphism of G;
  let H be Subgroup of G;
  assume A1: for h being Element of H holds phi.h in H;
  for y being object
  st y in rng(phi|H)
  holds y in the carrier of H
  proof
    let y be object;
    assume y in rng(phi|H);
    then consider x being object such that
    B1: x in dom(phi|H) and
    B2: y = (phi|H).x
    by FUNCT_1:def 3;
    B3: x in H by B1;
    then reconsider x as Element of H;
    x is Element of G by GROUP_2:42;
    then (phi|H).x = phi.x by B3,Th2;
    then B4: y = phi.x by B2;
    phi.x in H by A1;
    hence y in the carrier of H by B4;
  end;
  then rng(phi|H) c= the carrier of H by TARSKI:def 3;
  then the carrier of Image(phi|H) c= the carrier of H by GROUP_6:44;
  hence Image(phi|H) is Subgroup of H by GROUP_2:57;
end;

theorem Th48:
  for A being non empty Subset of G
  st (for phi being Automorphism of G
      holds phi .: A = A)
  holds gr A is characteristic
proof
  let A be non empty Subset of G;
  assume A1: for phi being Automorphism of G holds phi .: A = A;
  A2: for a being Element of A
  holds phi.a in A
  proof
    let a be Element of A;
    dom phi = the carrier of G by FUNCT_2:def 1;
    then a in dom phi;
    then phi.a in phi .: A by FUNCT_1:def 6;
    hence phi.a in A by A1;
  end;
  set H = gr A;
  A3: for phi being Automorphism of G holds Image(phi|H) is Subgroup of H
  proof
    let phi be Automorphism of G;
    B2: for h being Element of G
    st h in H
    holds phi.h in H
    proof
      let h be Element of G;
      assume h in H;
      then consider F1 being FinSequence of the carrier of G,
                    I being FinSequence of INT such that
      C2: len F1 = len I and
      C3: rng F1 c= A and
      C4: Product(F1 |^ I) = h
      by GROUP_4:28;
      deffunc F(Nat) = phi.(F1/.$1);
      consider F2 being FinSequence such that
      C5: len(F2) = len F1 and
      C6: for k being Nat st k in dom F2 holds F2.k = F(k)
      from FINSEQ_1:sch 2;
      C7: dom F2 = dom F1 by C5,FINSEQ_3:29;
      C8: F2 is FinSequence of the carrier of G & rng F2 c= A
      proof
        D1: for y being object st y in rng F2 holds y in A
        proof
          let y be object;
          assume y in rng F2;
          then consider k being object such that
          E2: k in dom F2 and
          E3: y = F2.k by FUNCT_1:def 3;
          reconsider k as Element of NAT by E2;
          set x = F1.k;
          x in rng F1 by FUNCT_1:def 3, E2, C7;
          then reconsider x as Element of A by C3;
          E4: x = F1/.k by E2,C7,PARTFUN1:def 6;
          y = F(k) by E2,E3,C6
           .= phi.(F1/.k)
           .= phi.(x) by E4;
          then y in A by A2;
          then E5: y is Element of A;
          thus thesis by E5;
        end;
        D2: rng F2 c= A by D1, TARSKI:def 3;
        for y being object st y in rng F2 holds y in the carrier of G
        proof
          let y be object;
          assume y in rng F2;
          then y in A by D1;
          hence y in the carrier of G;
        end;
        hence rng F2 c= the carrier of G by TARSKI:def 3;
        thus rng F2 c= A by D2;
      end;
      then reconsider F2 as FinSequence of the carrier of G;
      set h2 = Product(F2 |^ I);
      C9: (for k being Nat st k in dom F1
      holds F2.k = phi.(F1.k)) & len F1 = len I & len F2 = len I
      proof
        thus (for k being Nat st k in dom F1
        holds F2.k = phi.(F1.k))
        proof
          let k be Nat;
          assume D1: k in dom F1;
          then k in dom F2 by C7;
          then F2.k = F(k) by C6
                   .= phi.(F1/.k);
          hence F2.k = phi.(F1.k) by D1,PARTFUN1:def 6;
        end;
        thus len F1 = len I by C2;
        thus len F2 = len I by C2,C5;
      end;
      then phi.(Product(F1 |^ I)) = Product(F2 |^ I) by GROUP_9:125;
      then len F2 = len I & rng F2 c= A & Product(F2 |^ I) = phi.h
      by C4,C9,C8;
      hence phi.h in H by GROUP_4:28;
    end;
    for h being Element of H
    holds phi.h in H
    proof
      let h be Element of H;
      C1: h in H;
      h is Element of G by GROUP_2:42;
      then phi.h in H by B2,C1;
      hence thesis;
    end;
    hence Image(phi|H) is Subgroup of H by Th47;
  end;
  thus gr A is characteristic by A3,Th42;
end;

theorem Th49:
  G` is characteristic
proof
  [.1_G,1_G.] in commutators G;
  then A1: commutators G <> {};
  for phi being Automorphism of G holds phi .: commutators G =
  commutators G by Th46;
  then gr commutators G is characteristic by A1,Th48;
  hence thesis;
end;

theorem Th50:
  for G1,G2 being Group
  for H being Subgroup of G1
  for a being Element of G1
  for f being Homomorphism of G1,G2
  holds f.:(a * H) = (f.a) * (f .: H)
proof
  let G1,G2 be Group;
  let H be Subgroup of G1;
  let a be Element of G1;
  let f be Homomorphism of G1,G2;
  A1: dom f = the carrier of G1 by FUNCT_2:def 1;
  for y being object st y in f.:(a * H) holds y in (f.a)*(f.:H)
  proof
    let y be object;
    assume B1: y in f .: (a * H);
    then consider x being object such that
    B2: x in the carrier of G1 & x in (a * H) and
    B3: y = f.x
    by A1,FUNCT_1:def 6;
    consider h being Element of G1 such that
    B4: x = a*h & h in H
    by B2,GROUP_2:103;
    B5: y = f.(a*h) by B3,B4
         .= (f.a)*(f.h) by GROUP_6:def 6;
    dom f = the carrier of G1 & h in H & h in G1 by A1, B4, GROUP_2:40;
    then f.h in f.:(the carrier of H) by B4,FUNCT_1:def 6;
    then f.h in the carrier of (f.:H) by GRSOLV_1:8;
    then f.h in f.:H;
    then (f.a)*(f.h) in (f.a)*(f.:H) by GROUP_2:103;
    hence y in (f.a) * (f .: H) by B5;
  end;
  then A1: f.:(a * H) c= (f.a) * (f .: H) by TARSKI:def 3;
  for y being object st y in (f.a)*(f.:H) holds y in f.:(a * H)
  proof
    let y be object;
    assume B1: y in (f.a)*(f.:H);
    then consider g being Element of G2 such that
    B2: y = (f.a)*g and
    B3: g in (f.:H)
    by GROUP_2:103;
    g in Image(f|H) by B3,GRSOLV_1:def 2,def 3;
    then consider x being Element of H such that
    B4: g = (f|H).x
    by GROUP_6:45;
    B5: x in H & x is Element of G1 by GROUP_2:42;
    reconsider x as Element of G1 by GROUP_2:42;
    (f|H).x = f.x by B5,Th2;
    then B6: g = f.x by B4;
    B7: y = (f.a)*g by B2
         .= (f.a)*(f.x) by B6
         .= f.(a*x) by GROUP_6:def 6;
    B8: a*x in a*H by B5,GROUP_2:103;
    dom f = the carrier of G1 by FUNCT_2:def 1;
    then a*x in the carrier of G1 & dom f = the carrier of G1 by A1,B8;
    then (a*x) in dom f & (a*x) in a*H & y=f.(a*x) by A1,B7,B8;
    hence y in f.:(a * H) by A1,B7,B8,FUNCT_1:def 6;
  end;
  then A2: (f.a) * (f .: H) c= f.:(a * H) by TARSKI:def 3;
  thus f.:(a * H) = (f.a) * (f .: H) by A1,A2,XBOOLE_0:def 10;
end;

theorem Th51:
  for G1,G2 being Group
  for H being Subgroup of G1
  for a being Element of G1
  for f being Homomorphism of G1,G2
  holds f.:(H * a) = (f .: H) * (f.a)
proof
  let G1,G2 be Group;
  let H be Subgroup of G1;
  let a be Element of G1;
  let f be Homomorphism of G1,G2;
  A1: dom f = the carrier of G1 by FUNCT_2:def 1;
  for y being object st y in f.:(H * a) holds y in (f.:H)*(f.a)
  proof
    let y be object;
    assume B1: y in f .: (H * a);
    then consider x being object such that
    B2: x in the carrier of G1 & x in (H * a) and
    B3: y = f.x
    by A1,FUNCT_1:def 6;
    consider h being Element of G1 such that
    B4: x = h*a & h in H
    by B2,GROUP_2:104;
    B5: y = f.(h*a) by B3,B4
         .= (f.h)*(f.a) by GROUP_6:def 6;
    dom f = the carrier of G1 & h in H & h in G1 by A1, B4, GROUP_2:40;
    then f.h in f.:(the carrier of H) by B4,FUNCT_1:def 6;
    then f.h in the carrier of (f.:H) by GRSOLV_1:8;
    then f.h in f.:H;
    then (f.h)*(f.a) in (f.:H)*(f.a) by GROUP_2:104;
    hence thesis by B5;
  end;
  then A1: f.:(H * a) c= (f .: H) * (f.a) by TARSKI:def 3;
  for y being object st y in (f.:H)*(f.a) holds y in f.:(H * a)
  proof
    let y be object;
    assume B1: y in (f.:H)*(f.a);
    then consider g being Element of G2 such that
    B2: y = g*(f.a) and
    B3: g in (f.:H)
    by GROUP_2:104;
    g in Image(f|H) by B3,GRSOLV_1:def 2,def 3;
    then consider x being Element of H such that
    B4: g = (f|H).x
    by GROUP_6:45;
    B5: x in H & x is Element of G1 by GROUP_2:42;
    reconsider x as Element of G1 by GROUP_2:42;
    (f|H).x = f.x by B5,Th2;
    then B6: g = f.x by B4;
    B7: y = g*(f.a) by B2
         .= (f.x)*(f.a) by B6
         .= f.(x*a) by GROUP_6:def 6;
    B8: x*a in H*a by B5,GROUP_2:104;
    dom f = the carrier of G1 by FUNCT_2:def 1;
    then x*a in the carrier of G1 & dom f = the carrier of G1 by A1,B8;
    then (x*a) in dom f & (x*a) in H*a & y=f.(x*a) by A1,B7,B8;
    hence y in f.:(H * a) by A1,B7,B8,FUNCT_1:def 6;
  end;
  then A2: (f .: H) * (f.a) c= f.:(H * a) by TARSKI:def 3;
  thus f.:(H * a) = (f .: H)*(f.a) by A1,A2,XBOOLE_0:def 10;
end;

theorem Th52:
  for G being Group
  for N being strict normal Subgroup of G
  for phi being Automorphism of G
  holds Image(phi|N) is normal Subgroup of G
proof
  let G be Group;
  let N be strict normal Subgroup of G;
  let phi be Automorphism of G;
  set H = Image(phi|N);
  A1: H = phi .: N by GRSOLV_1:def 3;
  for g being Element of G
  holds g * H = H * g
  proof
    let g be Element of G;
    set f = (phi").g;
    f is Element of G;
    B1: phi.f = g by Th6;
    B2: f * N = N * f by GROUP_3:117;
    B3: phi .: (f * N) = (phi.f) * (phi .: N) by Th50
                      .= g * H by B1,A1;
    B4: phi .: (N * f) = (phi .: N)*(phi.f) by Th51
                      .= (phi .: N)*g by B1
                      .= H*g by A1;
    hence g * H = H * g by B2,B3,B4;
  end;
  hence H is normal Subgroup of G by GROUP_3:117;
end;

scheme :: Sch 3
  XResidualIsChar{G() -> Group, P[Group]} :
ex K being strict Subgroup of G()
st the carrier of K = meet {A where A is Subset of G() :
                            ex H being strict normal Subgroup of G()
                            st A = the carrier of H & P[G()./.H]} &
   K is characteristic
provided
A1: for phi being Automorphism of G()
    for N being strict normal Subgroup of G()
    st P[G()./.N]
    holds ex H being strict normal Subgroup of G()
          st H = Image(phi|N) & P[G()./.H] and
A2: ex H being strict normal Subgroup of G() st P[G()./.H]
proof
  defpred P2[Group] means ex N being strict normal Subgroup of G()
                          st the multMagma of N = the multMagma of $1 &
                             P[G() ./. N];
  set Fam = {A where A is Subset of G() :
             ex H being strict normal Subgroup of G()
             st A = the carrier of H & P[G()./.H]};
  set Fam2 = {A where A is Subset of G() :
              ex H being strict Subgroup of G()
              st A = the carrier of H & P2[H]};

  A3: for phi being Automorphism of G()
  for H being strict Subgroup of G()
  st P2[H]
  holds P2[Image(phi|H)]
  proof
    let phi be Automorphism of G();
    let H be strict Subgroup of G();
    assume B1: P2[H];

    then consider N being strict normal Subgroup of G() such that
    B2: the multMagma of N = the multMagma of H and
    B3: P[G()./.N];

    P[G()./.N] by B3;
    then P2[N];
    then consider N2 being strict normal Subgroup of G() such that
    B4: N2 = Image(phi|N) & P[G()./.N2]
    by A1;
    P2[(Image(phi|N))] by B4,Th52;
    hence P2[Image(phi|H)] by B2;
  end;
  A4: ex H being strict Subgroup of G() st P2[H] by A2;

  consider K being strict Subgroup of G() such that
  A5: the carrier of K = meet Fam2 and
  A6: K is characteristic
  from MeetIsChar(A3,A4);
  take K;
  for A being object
  holds A in Fam iff A in Fam2
  proof
    let A be object;
    thus A in Fam implies A in Fam2
    proof
      assume B1: A in Fam;
      then consider A0 being Subset of G() such that
      B2: A = A0 and
      B3: ex H being strict normal Subgroup of G()
      st A0 = the carrier of H & P[G()./.H];
      consider H being strict normal Subgroup of G() such that
      B4: A0 = the carrier of H and
      B5: P[G()./.H]
      by B3;
      B6: A0 = carr H & H is strict Subgroup of G() & P2[H] by B4,B5;
      then ex H2 being strict Subgroup of G() st A0 = carr H2 & P2[H2];
      then A0 in Fam2;
      hence thesis by B2;
    end;
    thus A in Fam2 implies A in Fam
    proof
      assume B1: A in Fam2;
      then consider A0 being Subset of G() such that
      B2: A = A0 and
      B3: ex H being strict Subgroup of G()
      st A0 = the carrier of H & P2[H];
      consider H being strict Subgroup of G() such that
      B4: A0 = the carrier of H and
      B5: P2[H]
      by B3;
      B6: ex N being strict normal Subgroup of G() st N=H & P[G()./.N] by B5;
      then A0 in Fam by B4;
      hence thesis by B2;
    end;
  end;
  then Fam = Fam2 by TARSKI:2;
  then the carrier of K = meet Fam by A5;
  hence thesis by A5,A6;
end;






scheme
  MeetIsMinimal{G() -> Group, P[set]} :
  ex H being strict Subgroup of G() st
  the carrier of H = meet {A where A is Subset of G() : ex K being strict Subgroup of G() st A = the carrier of K & P[K]} &
  (for K being strict Subgroup of G() st P[K] holds H is Subgroup of K)
provided
A1: ex H being strict Subgroup of G() st P[H]
proof
  set Fam = {A where A is Subset of G() : ex H being strict Subgroup of G() st A = the carrier of H & P[H]};
  consider H being strict Subgroup of G() such that
A2: the carrier of H = meet {A where A is Subset of G() :
                             ex K being strict Subgroup of G()
                             st A = the carrier of K & P[K]}
  from GROUP_4:sch 1(A1);
  take H;
  for K being strict Subgroup of G() st P[K] holds H is Subgroup of K
  proof
    let K be strict Subgroup of G();
    assume P[K];
    then carr K in Fam;
    then meet Fam c= carr K by SETFAM_1:3;
    then carr H c= carr K by A2;
    then H is Subgroup of K by GROUP_2:57;
    hence thesis;
  end;
  hence thesis by A2;
end;

theorem Th53:
  for G being Group
  for H1,H2 being Subgroup of G
  st H1 is Subgroup of H2
  for a being Element of G
  holds H1 |^ a is Subgroup of H2 |^ a
proof
  let G be Group;
  let H1,H2 be Subgroup of G;
  assume A1: H1 is Subgroup of H2;
  let a be Element of G;
  for h being Element of G
  st h in H1 |^ a
  holds h in H2 |^ a
  proof
    let h be Element of G;
    assume B1: h in H1 |^ a;
    then consider g being Element of G such that
    B2: h = g |^ a and
    B3: g in H1
    by GROUP_3:58;
    g in H2 by A1,B3,GROUP_2:40;
    then g |^ a in H2 |^ a by GROUP_3:58;
    hence thesis by B2;
  end;
  hence H1 |^ a is Subgroup of H2 |^ a by GROUP_2:58;
end;

scheme
  MeetOfNormsIsNormal{G() -> Group, P[set]} :
  for H being strict Subgroup of G()
  st the carrier of H = meet {A where A is Subset of G() : ex N being strict Subgroup of G() st A = the carrier of N & N is normal & P[N]}
  holds H is strict normal Subgroup of G()
provided
A1: ex H being strict normal Subgroup of G() st P[H]
proof
  defpred IsNorm[Subgroup of G()] means $1 is normal Subgroup of G();
  set Fam = {A where A is Subset of G() : ex N being strict Subgroup of G() st A = the carrier of N & N is normal & P[N]};
  let H be strict Subgroup of G();
  assume A2: the carrier of H = meet Fam;
  A3: Fam <> {}
  proof
    consider N being strict normal Subgroup of G() such that
    B1: P[N]
    by A1;
    carr N in Fam by B1;
    hence thesis;
  end;
  A4: for N being strict normal Subgroup of G() st P[N] holds H is Subgroup of N
  proof
    let N be strict normal Subgroup of G();
    assume P[N];
    then carr N in Fam;
    then meet Fam c= carr N by SETFAM_1:3;
    then the carrier of H c= carr N by A2;
    then H is Subgroup of N by GROUP_2:57;
    hence thesis;
  end;
  A5: for a being Element of G()
  for N being strict normal Subgroup of G() st P[N]
  holds H |^ a is Subgroup of N
  proof
    let a be Element of G();
    let N be strict normal Subgroup of G();
    assume B1: P[N];
    then H is Subgroup of N by A4;
    then H |^ a is Subgroup of N |^ a by Th53;
    hence H |^ a is Subgroup of N by GROUP_3:def 13;
  end;
  A6: for N being strict normal Subgroup of G() st carr N in Fam
  holds P[N]
  proof
    let N be strict normal Subgroup of G();
    assume B1: carr N in Fam;
    consider A being Subset of G() such that
    B2: A = carr N;
    A in Fam by B1,B2;
    then consider A0 being Subset of G() such that
    B3: A = A0 and
    B4: ex H0 being strict Subgroup of G() st A0 = the carrier of H0 & H0 is normal & P[H0];
    consider H0 being strict Subgroup of G() such that
    B5: A0 = the carrier of H0 & H0 is normal & P[H0]
    by B4;
    carr H0 = carr N by B2,B3,B5;
    then H0 = N by GROUP_2:59;
    hence P[N] by B5;
  end;
  A7: for a being Element of G()
  for N being strict normal Subgroup of G() st carr N in Fam
  holds H |^ a is Subgroup of N
  proof
    let a be Element of G();
    let N be strict normal Subgroup of G();
    assume B1: carr N in Fam;
    then P[N] by A6;
    then H is Subgroup of N by A4;
    then H |^ a is Subgroup of N |^ a by Th53;
    hence H |^ a is Subgroup of N by GROUP_3:def 13;
  end;
  A8: for a being Element of G()
  for N being strict normal Subgroup of G() st carr N in Fam
  holds carr(H |^ a) c= carr N
  proof
    let a be Element of G();
    let N be strict normal Subgroup of G();
    assume B1: carr N in Fam;
    then H |^ a is Subgroup of N by A7;
    hence carr(H |^ a) c= carr N by GROUP_2:def 5;
  end;

  for a being Element of G()
  holds H |^ a is Subgroup of H
  proof
    let a be Element of G();
    B1: Fam <> {} by A3;
    B2: (for N being strict normal Subgroup of G() st carr N in Fam
    holds carr(H |^ a) c= carr N) by A3,A8,GROUP_2:def 5;
    B3: for A being Subset of G() st A in Fam holds carr(H |^ a) c= A
    proof
      let A be Subset of G();
      assume C0: A in Fam;
      then consider A0 being Subset of G() such that
      C1: A = A0 and
      C2: ex H0 being strict Subgroup of G() st A0 = the carrier of H0 & H0 is normal & P[H0];
      consider H0 being strict Subgroup of G() such that
      C3: A0 = the carrier of H0 & H0 is normal & P[H0]
      by C2;
      reconsider H0 as strict normal Subgroup of G() by C3;
      carr H0 in Fam by C0,C1,C3;
      then carr(H |^ a) c= carr H0 by B1,B2;
      hence carr(H |^ a) c= A by C1,C3;
    end;
    for x being object st x in carr (H |^ a) holds x in meet Fam
    proof
      let x be object;
      assume C1: x in carr(H |^ a);
      for A being set st A in Fam holds x in A
      proof
        let A be set;
        assume C2: A in Fam;
        then consider A0 being Subset of G() such that
        C3: A0 = A and
        C4: ex H0 being strict Subgroup of G() st A0 = the carrier of H0 & H0 is normal & P[H0];
        carr(H |^ a) c= A0 by C2,C3,B3;
        hence thesis by C1,C3;
      end;
      hence thesis by B1,SETFAM_1:def 1;
    end;
    then carr (H |^ a) c= meet Fam by B1,SETFAM_1:def 1;
    then carr (H |^ a) c= carr H by A2;
    hence thesis by GROUP_2:57;
  end;
  then H is normal by GROUP_3:122;
  hence thesis;
end;

theorem Th54:
  for G being Group
  for X being finite set
  st X <> {} & (for A being Element of X holds ex N being strict normal Subgroup of G st A = the carrier of N)
  holds ex N being strict normal Subgroup of G st the carrier of N = meet X
proof
  let G be Group;
  let X be finite set;
  assume A1: X <> {};
  assume A2: for A being Element of X holds ex N being strict normal Subgroup of G st A = the carrier of N;
  defpred P[Group] means $1 is normal Subgroup of G & the carrier of $1 in X;
  set Fam = {A where A is Subset of G : ex N being strict Subgroup of G st A = the carrier of N & P[N]};
  set Fam2 = {A where A is Subset of G : ex N being strict Subgroup of G st A = the carrier of N & N is normal & P[N]};
  A3: ex H being strict Subgroup of G st P[H]
  proof
    X <> {} by A1;
    then X is non empty;
    then ex A being object st A in X by XBOOLE_0:def 1;
    then consider A being object such that
    B1: A in X;
    reconsider A as Element of X by B1;
    consider H being strict normal Subgroup of G such that
    B2: A = the carrier of H
    by A2;
    take H;
    the carrier of H in X by B1,B2;
    hence P[H];
  end;

  consider N being strict Subgroup of G such that
  A4: the carrier of N = meet Fam
  from GROUP_4:sch 1(A3);
  for A being object
  holds A in Fam iff A in Fam2
  proof
    let A be object;
    thus A in Fam implies A in Fam2
    proof
      assume B1: A in Fam;
      then consider A0 being Subset of G such that
      B2: A = A0 and
      B3: ex N being strict Subgroup of G st A0 = the carrier of N & P[N];

      consider N being strict Subgroup of G such that
      B4: A0 = the carrier of N & P[N]
      by B3;
      B5: N is normal by B4;
      hence A in Fam2 by B2,B3,B4,B5;
    end;
    thus A in Fam2 implies A in Fam
    proof
      assume B1: A in Fam2;
      then consider A0 being Subset of G such that
      B2: A = A0 and
      B3: ex N being strict Subgroup of G st A0 = the carrier of N & N is normal & P[N];
      thus A in Fam by B2,B3;
    end;
  end;
  then A5: Fam = Fam2 by TARSKI:2;
  B3: ex H being strict normal Subgroup of G st P[H]
  proof
    consider H being strict Subgroup of G such that
    B1: P[H]
    by A3;
    H is strict normal Subgroup of G & the carrier of H in X by B1;
    then reconsider H as strict normal Subgroup of G;
    take H;
    thus thesis by B1;
  end;
  A6: for H being strict Subgroup of G
  st the carrier of H = meet Fam2
  holds H is strict normal Subgroup of G
  from MeetOfNormsIsNormal(B3);
  then N is normal by A4,A5;
  then reconsider N as strict normal Subgroup of G;
  take N;

  for A being object
  holds A in Fam iff A in X
  proof
    let A be object;
    thus A in Fam implies A in X
    proof
      assume B1: A in Fam;
      then consider A0 being Subset of G such that
      B3: A = A0 and
      B2: ex N being strict Subgroup of G st A0 = the carrier of N & P[N];

      consider N being strict Subgroup of G such that
      B4: A0 = the carrier of N & P[N]
      by B2;
      reconsider N as strict normal Subgroup of G by B4;
      the carrier of N in X by B4;
      hence thesis by B2,B3,B4;
    end;
    thus A in X implies A in Fam
    proof
      assume B1: A in X;
      then consider N being strict normal Subgroup of G such that
      B2: A = the carrier of N
      by A2;
      B3: P[N] by B1,B2;
      A is Subset of G by B2,GROUP_2:def 5;
      hence A in Fam by B2,B3;
    end;
  end;
  then Fam = X by TARSKI:2;
  hence the carrier of N = meet X by A4,A5,TARSKI:2;
end;

:: TODO: formalize the universal property of product groups
:: If F is associative Group-like multMagma-Family of I,
:: and PHI is Family of Homomorphism from Z to F
:: ex phi being Homomorphism of Z,product F st for i being object st i in I holds
:: for z being Element of Z holds (PHI.i).z = ((pi i)*phi).z
reserve I for set;
reserve i for object;
theorem Th55:
  for G being Group
  for X being set
  st X <> {} & (for A being Element of X
                holds ex N being strict normal Subgroup of G
                st A = the carrier of N)
  for I being set
  st card I = card X
  for F being associative Group-like multMagma-Family of I
  st (for i being Element of I
      holds ex N being strict normal Subgroup of G st the carrier of N in X & F.i = G./.N) &
     (for N being strict normal Subgroup of G st the carrier of N in X
      holds ex i being Element of I st F.i = G./.N)
  holds ex H being Group st H = product F &
                         ex N being strict normal Subgroup of G
                            st the carrier of N = meet X &
                         ex phi being Homomorphism of G,product F
                            st Image(phi),G./.N are_isomorphic
proof
  let G be Group;
  let X be set;
  assume A1: X <> {};
  assume A2: for A being Element of X
             holds ex N being strict normal Subgroup of G st A = the carrier of N;
  let I be set;
  assume A3: card I = card X;
  let F be associative Group-like multMagma-Family of I;
  assume A4: for i being Element of I
      holds ex N being strict normal Subgroup of G st the carrier of N in X & F.i = G./.N;
  assume A5: for N being strict normal Subgroup of G st the carrier of N in X
      holds ex i being Element of I st F.i = G./.N;
  set Y = Subgroups G;
  defpred PNP[object,object] means ex N being normal Subgroup of G st N=$2 & F.$1 = G./.N;

  A40: for x being object st x in I ex y being object st y in Y & PNP[x,y]
  proof
    let x be object;
    assume B1: x in I;
    then reconsider x as Element of I;
    consider N being strict normal Subgroup of G such that
    B1: the carrier of N in X and
    B2: F.x = G./.N
    by A4;
    N is strict Subgroup of G;
    then reconsider y = N as Element of Y by GROUP_3:def 1;
    take y;
    thus y in Y;
    ex N0 being normal Subgroup of G st N0=y & F.x = G./.N0 by B2;
    y = N;
    then PNP[x,y] by B2;
    hence thesis;
  end;
  consider FN being Function of I,Y such that
  A41: for i being object st i in I holds PNP[i,FN.i]
  from FUNCT_2:sch 1(A40);

  consider H being Group such that
  A6: H = product F;
  take H;
  thus C1: H = product F by A6;
  defpred P[Group] means the carrier of $1 in X;
  set Fam = {A where A is Subset of G : ex N being strict Subgroup of G
                                        st A = the carrier of N & P[N]};
  A7: ex H being strict Subgroup of G st P[H]
  proof
    X <> {} by A1;
    then X is non empty;
    then ex A being object st A in X by XBOOLE_0:def 1;
    then consider A being object such that
    B1: A in X;
    reconsider A as Element of X by B1;
    consider H being strict normal Subgroup of G such that
    B2: A = the carrier of H
    by B1,A2;
    take H;
    the carrier of H in X by B1,B2;
    hence P[H];
  end;
  consider N being strict normal Subgroup of G such that
  A7: the carrier of N = meet X
  by A1,A2,Th54;
::>,4
  take N;
  thus C2: the carrier of N = meet X by A7;

  defpred PhiP[Element of G, Element of product F] means
  ex f being Function st $2 = f & dom f = dom F & (for i being object st i in dom F
  holds ex Ni being strict normal Subgroup of G st FN.i=Ni & f.i = (nat_hom Ni).$1);

  A8: for x being Element of G ex y being Element of product F st PhiP[x,y];
::>                                                                       *4

  consider phi being Function of G,product F such that
  A9: for g being Element of G holds PhiP[g,phi.g]
  from FUNCT_2:sch 3(A8);

  for a,b being Element of G holds phi.(a*b) = phi.a * phi.b
  proof
    let a,b be Element of G;
    PhiP[a*b,phi.(a*b)] by A9;
    then consider f being Function such that
    B1: f = phi.(a*b) and
    B2: dom f = dom F and
    B3: for i being object st i in dom F holds ex Ni being strict normal Subgroup of
        G st FN.i = Ni & f.i = (nat_hom Ni).(a * b);

    B4: for i being object st i in dom F
    holds ex Ni being strict normal Subgroup of G
    st FN.i=Ni & f.i = (nat_hom Ni).a * (nat_hom Ni).b
    proof
      let i be object;
      assume D1: i in dom F;
      then consider Ni being strict normal Subgroup of G such that
      D2: FN.i = Ni and
      D3: f.i = (nat_hom Ni).(a * b)
      by B3;
      take Ni;
      thus FN.i=Ni by D2;
      thus f.i = (nat_hom Ni).a * (nat_hom Ni).b by D3, GROUP_6:def 6;
    end;
    set pa = phi.a;
    set pb = phi.b;
    set pab = phi.(a*b);
    pa is Element of product F & pb is Element of product F;
    then for i being set st i in I ex Fi being Group, h being Function st Fi = F.i &
    h = (the multF of product F).(pa,pb) :: & h.i = (the multF of Fi).(pa.i, pb.i)
    by GROUP_7:def 2;
::>  *4

    PhiP[a,phi.a] by A9;
    then consider fa being Function such that
    B5: fa = phi.a & dom fa = dom F and
    B6: for i being object st i in dom F holds ex Ni being strict normal Subgroup of
        G st FN.i = Ni & fa.i = (nat_hom Ni).(a * b);
::>                                                *4

    PhiP[a*b, phi.a * phi.b] by B1,B2,B3,B4;
::>                           *4
    hence phi.(a*b) = phi.a * phi.b by A9;
::>                                  *4
  end;
  then reconsider phi as Homomorphism of G,product F by GROUP_6:def 6;

  the carrier of Ker phi = meet X;
::>                             *4
  then C3: N = Ker phi by A7, GROUP_2:59;
  take phi;
  thus Image(phi),G./.N are_isomorphic by C3,GROUP_6:78;
end;

theorem Th56:
  for G being Group
  for X being set
  st X<>{} & (for A being object st A in X holds A is normal Subgroup of G)
  for I being set
  st card I = card X
  holds ex F being associative Group-like multMagma-Family of I st
  (for i being Element of I
   holds ex N being normal Subgroup of G st N in X & F.i = G./.N) &
  (for N being normal Subgroup of G st N in X
   holds ex i being Element of I st F.i = G./.N);
::>                                            *4

theorem Th57:
  for Fam being set
  st Fam <> {} & (for G being Element of Fam holds G is Group)
  holds ex F being associative Group-like multMagma-Family of Fam
  st (for G being Group st G in Fam holds F.G=G)
proof
  let Fam be set;
  assume A1: Fam <> {};
  assume A2: for G being Element of Fam holds G is Group;
  set F = id Fam;
  A3: F = id Fam;
  dom F = Fam;
  then F is total Fam-defined Function;
  then F is ManySortedSet of Fam;
  A3: for y being set st y in rng F holds y is non empty multMagma
  proof
    let y be set;
    assume B1: y in rng F;
    then y is Element of Fam;
    then y is Group by A2;
    hence thesis;
  end;
  then F is multMagma-yielding ManySortedSet of Fam by GROUP_7:def 1;
  then reconsider F as multMagma-Family of Fam;
  F is associative Group-like multMagma-Family of Fam
  proof
    for i being set st i in Fam ex Fi being Group-like non empty
    multMagma st Fi = F.i
    proof
      let i be set;
      assume i in Fam;
      then reconsider i as Element of Fam;
      i is Group by A2;
      then consider Fi being Group such that
      D1: Fi = i
      by A2;
      F.i=Fi by D1,FUNCT_1:17;
      hence thesis;
    end;
    then B1: F is Group-like by GROUP_7:def 3;
    for i being set st i in Fam ex Fi being associative non empty
    multMagma st Fi = F.i
    proof
      let i be set;
      assume i in Fam;
      then reconsider i as Element of Fam;
      i is Group by A2;
      then consider Fi being Group such that
      D1: Fi = i
      by A2;
      F.i=Fi by D1,FUNCT_1:17;
      hence thesis;
    end;
    then B2: F is associative by GROUP_7:def 4;
    thus thesis by B1,B2;
  end;
  then reconsider F as associative Group-like multMagma-Family of Fam;
  take F;
  let G be Group;
  assume A3: G in Fam;
  thus F.G=G by A3,FUNCT_1:17;
end;

theorem Th58:
  for Fam being finite set
  st Fam <> {} & (for G being Element of Fam holds G is Group)
  holds ex F being associative Group-like multMagma-Family of Seg (card Fam)
  st F is one-to-one & (for i being Nat st i in Seg (card Fam) holds ex G
  being Group st G in Fam & F.i=G)
proof
  let Fam be finite set;
  assume A1: Fam <> {};
  assume A2: for G being Element of Fam holds G is Group;
  set F = canFS Fam;
  set n = len F;
  A21: n = len F;
  A3: len F = card Fam by FINSEQ_1:93;
  A31: n = card Fam by A21,A3;
  F is PartFunc of NAT,Fam;
  A4: F is one-to-one onto by FINSEQ_1:def 19;
  F is Function of Seg n,Fam
  proof
    B1: dom F = Seg n by A1,FINSEQ_1:def 2,def 3;
    then reconsider F1 = F|(dom F) as PartFunc of Seg n,Fam by PARTFUN1:10;
    set F = F1;
    F is PartFunc of Seg n,Fam &
    dom F = Seg n by B1;
    then F is quasi_total by A1,FUNCT_2:def 1;
    hence thesis;
  end;
  then reconsider F as Function of Seg n,Fam by A4;
  A40: rng F = Fam by A4;
  A5: F is ManySortedSet of (Seg n)
  proof
    B1: dom F = Seg (card Fam) by A3,FINSEQ_1:def 3;
    then B2: F is (Seg n)-defined Function by RELAT_1:def 16;
    F is quasi_total Function of Seg n,Fam;
    then dom F = (Seg n) by B1,A3;
    then F is total by B1,PARTFUN1:def 2;
    hence thesis;
  end;
  A6: for y being set st y in rng F holds y is non empty multMagma
  proof
    let y be set;
    assume B1: y in rng F;
    then y is Element of Fam;
    then y is Group by A2;
    hence thesis;
  end;
  then F is multMagma-yielding by GROUP_7:def 1;
  then F is multMagma-yielding ManySortedSet of Seg n by A5,A6,GROUP_7:def 1;
  then reconsider F as multMagma-Family of Seg n;
  F is associative Group-like multMagma-Family of Seg n
  proof
    for i being set st i in Seg n ex Fi being Group-like non empty
    multMagma st Fi = F.i
    proof
      let i be set;
      assume D1: i in Seg n;
      then reconsider i as Element of Seg n;
      dom F = Seg n by A3,FINSEQ_1:def 3;
      then i in dom F by D1;
      then F.i in rng F by FUNCT_1:3;
      then F.i in Fam by A40;
      then F.i is Element of Fam;
      then F.i is Group by A2;
      then consider Fi being Group such that
      D2: Fi = F.i
      by A2;
      F.i=Fi by D2,FUNCT_1:17;
      hence thesis;
    end;
    then B1: F is Group-like by GROUP_7:def 3;
    for i being set st i in Seg n ex Fi being associative non empty
    multMagma st Fi = F.i
    proof
      let i be set;
      assume D1: i in Seg n;
      then reconsider i as Element of Seg n;
      dom F = Seg n by A3,FINSEQ_1:def 3;
      then i in dom F by D1;
      then F.i in rng F by FUNCT_1:3;
      then F.i in Fam by A40;
      then F.i is Element of Fam;
      then F.i is Group by A2;
      then consider Fi being Group such that
      D2: Fi = F.i
      by A2;
      F.i=Fi by D2,FUNCT_1:17;
      hence thesis;
    end;
    then B2: F is associative by GROUP_7:def 4;
    thus thesis by B1,B2;
  end;
  then reconsider F as associative Group-like multMagma-Family of Seg
  (card Fam) by A31;
  take F;
  thus F is one-to-one by A4;
  let i be Nat;
  assume A10: i in Seg (card Fam);
  dom F = Seg n by A3,FINSEQ_1:def 3;
  then i in dom F by A31,A10;
  then F.i in rng F by FUNCT_1:3;
  then A11: F.i in Fam by A40;
  then F.i is Element of Fam;
  then A12: F.i is Group by A2;
  hence thesis by A11;
end;

theorem Th59:
  for G being finite Group
  for X being Subset of Subgroups G
  holds X is finite
proof
  let G be finite Group;
  let X be Subset of Subgroups G;
  X c= Subgroups G & Subgroups G is finite by GROUP_3:15;
  hence X is finite by FINSET_1:1;
end;



theorem Th60:
  for G being Group
  for Fam being set
  st Fam<>{} & (for A being Element of Fam holds ex N being normal
  Subgroup of G st A = the carrier of N)
  for I being set
  st card I = card Fam
  holds ex F being associative Group-like multMagma-Family of I st
  (for i being Element of I
   holds ex N being normal Subgroup of G
         st the carrier of N in Fam & F.i = G./.N) &
  (for N being normal Subgroup of G st the carrier of N in Fam
  holds ex i being Element of I st F.i=G./.N);
:: proof
::   let G be Group;
::   let Fam be set;
::   assume A1: Fam<>{};
::   assume A2: for A being Element of Fam
::              holds ex N being normal Subgroup of G st A = the carrier of N;
::   let I be set;
::   assume A3: card I = card Fam;
::   consider F being associative Group-like multMagma-Family of I;
:: ::>                                                            *403
::   take F;
::   thus (for i being Element of I
::         holds ex N being normal Subgroup of G
::               st the carrier of N in Fam & F.i = G./.N)
::   proof
::     let i be Element of I;
::     consider N being normal Subgroup of G;
:: ::>                                      *403
::     take N;
::     thus the carrier of N in Fam;
:: ::>                            *4
::     thus F.i = G./.N;
:: ::>                *4
::   end;
::   let N be normal Subgroup of G;
::   assume Z3: the carrier of N in Fam;
::   consider i being Element of I;
:: ::>                            *403
::   take i;
::   thus F.i=G./.N;
:: ::>            *4
:: end;

theorem Th61:
  for G being Group
  ex X being set
  st (for N being normal Subgroup of G
      holds G./.N in X);
::>                   *4

theorem Th62:
  for G being Group
  for Fam being non empty set
  st (for N being Element of Fam holds N is normal Subgroup of G)
  holds ex F being associative Group-like multMagma-Family of Fam
  st (for N being normal Subgroup of G st N in Fam holds F.N=G./.N)
proof
  let G be Group;
  let Fam be non empty set;
  defpred P[object,object] means ex N being normal Subgroup of G st $1=N & $2=G./.N;
  assume A1: for N being Element of Fam holds N is normal Subgroup of G;
  A2: for x,y1,y2 being object st x in Fam & P[x,y1] & P[x,y2] holds y1=y2;
  A3: for x being object st x in Fam ex y being object st P[x,y]
  proof
    let x be object;
    assume B1: x in Fam;
    then x is normal Subgroup of G by A1;
    then reconsider x as normal Subgroup of G;
    consider N being normal Subgroup of G such that
    B2: x = N by Def10;
    consider y being Group such that
    B3: y = G./.N;
    reconsider y as object;
    take y;
    B5: P[x,y] by B2,B3;
    hence thesis;
  end;

  consider F being Function such that
  A4: dom F = Fam and
  A5: for x being object st x in Fam holds P[x, F.x]
  from FUNCT_1:sch 2(A2,A3);

  A6: for x being normal Subgroup of G st x in Fam holds F.x = G./.x
  proof
    let x be normal Subgroup of G;
    assume B1: x in Fam;
    P[x, F.x] by A4,A5,B1;
    then consider N being normal Subgroup of G such that
    B2: x = N and
    B3: F.x = G./.N;
    thus F.x = G./.x by B2,B3;
  end;  
  set codomain = rng F;
  A7: codomain <> {}
  proof
    Fam is non empty;
    then consider x being object such that
    B1: x in Fam
    by XBOOLE_0:def 1;
    reconsider x as Element of Fam by B1;
    F.x in rng F by A4,FUNCT_1:3;
    then F.x in codomain;
    hence thesis by XBOOLE_0:def 1;
  end;
  A8: for y being Element of codomain holds y is Group
  proof
    let y be Element of codomain;
    y in codomain by A7;
    then y in rng F;
    then consider x being object such that
    B1: x in dom F and
    B2: y = F.x
    by FUNCT_1:def 3;
    P[x, y] by B1,B2,A4,A5;
    then consider N being normal Subgroup of G such that
    B3: x = N and
    B4: y = G./.N;
    thus y is Group by B4;
  end;

  
  reconsider F as Function of Fam,codomain by A4,FUNCT_2:1;
  A9: F is Function of Fam,codomain by FUNCT_2:1;
  F is total Fam-defined Function by A4,A6,A7,FUNCT_2:def 1;
  then A10: F is ManySortedSet of Fam;

  A11: for y being set st y in rng F holds y is non empty multMagma
  proof
    let y be set;
    assume B1: y in rng F;
    then consider x being object such that
    B2: x in dom F and
    B3: y = F.x
    by FUNCT_1:def 3;
    x is Element of dom F by B2;
    then x is normal Subgroup of G by B2,A1;
    then reconsider x as normal Subgroup of G;
    y in rng F by A4, B2, B3, FUNCT_1:3;
    then y is Element of codomain;
    then y is Group by A8;
    hence thesis;
  end;
  then F is multMagma-yielding ManySortedSet of Fam by A10,GROUP_7:def 1;
  then reconsider F as multMagma-Family of Fam;
  F is associative Group-like multMagma-Family of Fam
  proof
    for i being set st i in Fam ex Fi being Group-like non empty
    multMagma st Fi = F.i
    proof
      let i be set;
      assume D1: i in Fam;
      then reconsider i as normal Subgroup of G by A1;
      consider Fi being Group such that
      D2: Fi = G./.i
      by A6;
      F.i = G./.i by D1,A6
      .= Fi by D2;
      hence thesis;
    end;
    then B1: F is Group-like by GROUP_7:def 3;
    for i being set st i in Fam ex Fi being associative non empty
    multMagma st Fi = F.i
    proof
      let i be set;
      assume D1: i in Fam;
      then reconsider i as normal Subgroup of G by A1;
      consider Fi being Group such that
      D2: Fi = G./.i
      by A6;
      F.i = G./.i by D1,A6
      .= Fi by D2;
      hence thesis;
    end;
    then B2: F is associative by GROUP_7:def 4;
    thus thesis by B1,B2;
  end;
  then reconsider F as associative Group-like multMagma-Family of Fam;

  take F;
  let N be normal Subgroup of G;
  assume A8: N in Fam;
  hence F.N=G./.N by A6;
end;


scheme :: Sch 3
  PResidualIsChar{G() -> finite Group, P[set]} :
  ex K being strict normal Subgroup of G()
  st P[G()./.K] &
     (for N being strict normal Subgroup of G()
      holds P[G()./.N] iff K is Subgroup of N) &
     K is characteristic
provided
P0: ex H being strict normal Subgroup of G() st P[G()./.H] and
P1: for G1,G2 being Group
    st G1,G2 are_isomorphic & P[G1]
    holds P[G2] and
P2: for H being Group
    st P[H]
    holds (for K being Subgroup of H holds P[K]) and
P3: for G being Group
    for H1,H2 being Subgroup of G
    st P[H1]
    holds P[H1 /\ H2] and
P4: for G being Group
    st P[G]
    for N being normal Subgroup of G holds P[G./.N] and
P5: for I being set for F being associative Group-like multMagma-Family
    of I st (for i being Element of I holds P[F.i]) holds P[product F]
proof
  defpred P2[set] means ex N being strict normal Subgroup of G()
                        st $1 = N & P[G()./.N];
  defpred P3[set] means ex H being strict Subgroup of G()
                        st $1 = H & H is normal & P2[H];
  Q0: ex H being strict normal Subgroup of G() st P3[H] by P0;
  Q2: for H being strict normal Subgroup of G() st P3[H]
  holds (for N being strict normal Subgroup of G()
         st H is Subgroup of N holds P3[N])
  proof
    let H be strict normal Subgroup of G();
    assume B1: P3[H];
    let N be strict normal Subgroup of G();
    assume B2: H is Subgroup of N;
    then N./.((N,H) `*`) is normal Subgroup of G()./.H by GROUP_6:29;
    then consider J being normal Subgroup of G()./.H such that
    B3: J = N./.((N,H) `*`);
    B4: P[(G()./.H)./.J] by B1,P4;
    (G()./.H)./.J,G()./.N are_isomorphic by B2,B3,GROUP_6:80;
    then P[G()./.N] by B4,P1;
    hence P3[N];
  end;

  A1: ex H being strict Subgroup of G() st P3[H] by P0;
  set Fam = {A where A is Subset of G() :
             ex H being strict Subgroup of G()
             st A = the carrier of H & P3[H]};
  set Fam2 = {A where A is Subset of G() :
              ex N being strict Subgroup of G()
              st A = the carrier of N & N is normal & P2[N]};
  consider K being strict Subgroup of G() such that
  A2: the carrier of K = meet Fam and
  A3: for N being strict Subgroup of G() st P3[N] holds K is Subgroup of N
  from MeetIsMinimal(A1);
  for A being object holds A in Fam iff A in Fam2
  proof
    let A be object;
    thus A in Fam implies A in Fam2
    proof
      assume A in Fam;
      then consider A0 being Subset of G() such that
      B1: A0 = A and
      B2: ex H0 being strict Subgroup of G() st A0 = the carrier of H0 &
          P3[H0];
      consider H0 being strict Subgroup of G() such that
      B3: A0 = the carrier of H0 & P3[H0]
      by B2;
      H0 is normal & P2[H0] by B3;
      then the carrier of H0 in Fam2 by B3;
      hence thesis by B1,B3;
    end;
    thus A in Fam2 implies A in Fam
    proof
      assume A in Fam2;
      then consider A0 being Subset of G() such that
      B1: A0 = A and
      B2: ex N being strict Subgroup of G() st A0 = the carrier of N &
          N is normal & P2[N];
      consider N being strict Subgroup of G() such that
      B3: A0 = the carrier of N & N is normal & P2[N]
      by B2;
      P3[N] by B3;
      then carr N in Fam;
      hence thesis by B1,B3;
    end;
  end;
  then A9: Fam = Fam2 by TARSKI:2;
  then meet Fam = meet Fam2;
  then A6: the carrier of K = meet Fam2 by A2;
  A7: ex H1 being strict normal Subgroup of G() st P2[H1] by A1;
  for H0 being strict Subgroup of G()
  st the carrier of H0 = meet Fam2
  holds H0 is strict normal Subgroup of G() from MeetOfNormsIsNormal(A7);
  then reconsider K as strict normal Subgroup of G() by A6;
  take K;

  A8: Fam <> {}
  proof
    consider H being strict normal Subgroup of G() such that
    B1: P[G()./.H]
    by P0;
    carr H in Fam by B1;
    hence thesis;
  end;
  A10: for A being Element of Fam
    holds ex N0 being strict normal Subgroup of G()
    st A = the carrier of N0 & P3[N0]
  proof
      let A be Element of Fam;
      A in Fam by A8,SUBSET_1:def 1;
      then A in Fam2 by A9;
      then consider A0 being Subset of G() such that
      D1: A = A0 and
      D2: ex N0 being strict Subgroup of G() st A0 = the carrier of N0
          & N0 is normal & P2[N0];
      consider N0 being strict normal Subgroup of G() such that
      D3: A0 = the carrier of N0 & N0 is normal & P2[N0]
      by D2;
      take N0;
      thus thesis by D1,D3;
  end;

:: for Fam being finite set
::  st Fam <> {} & (for G being Element of Fam holds G is Group)
::  holds ex F being associative Group-like multMagma-Family of Seg (card Fam)
::  st F is one-to-one & (for i being Nat st i in Seg (card Fam) holds ex G
::  being Group st G in Fam & F.i=G)
  set Fam = {A where A is Subset of G() :
             ex H being strict Subgroup of G()
             st A = the carrier of H & P3[H]};
  set GFam = {N0 where N0 is Element of Subgroups G() :
              P3[N0]};
  A11: GFam <> {}
  proof
    consider H0 being strict normal Subgroup of G() such that
    B1: P[G()./.H0] by P0;
    P3[H0] & H0 in Subgroups G() by B1,GROUP_3:def 1;
    then H0 in GFam;
    hence thesis;
  end;

  A12: for N0 being Element of GFam
  holds N0 is strict normal Subgroup of G()
  proof
    let N0 be Element of GFam;
    B1: N0 in GFam by A11,SUBSET_1:def 1;
    then consider H0 being Element of Subgroups G() such that
    B2: N0 = H0 & P3[H0];
    P3[N0] by B2;
    then P2[N0];
    then consider N1 being strict normal Subgroup of G() such that
    B3: N0 = N1 & P[G()./.N1];
    N1 is strict normal Subgroup of G() & N0 = N1 by B3;
    hence N0 is strict normal Subgroup of G();
  end;
  consider GFam1 being set such that
  A13: for N being object holds N is normal Subgroup of G() iff N in GFam1;
::>                                                                      *4
::  A13: for N being normal Subgroup of G() holds N in GFam1;

  consider GFam2 being set such that
  A14: for N being normal Subgroup of G() holds G()./.N in GFam2
  by Th61;
::>,4
  set GFam3 = {N1 where N1 is Element of GFam2 : P[N1]};
  
  A15: for N0 being Element of GFam
  ex N1 being strict normal Subgroup of G()
  st N0=N1 & G()./.N1 in GFam2
  proof
    let N0 be Element of GFam;
    B1: N0 is strict normal Subgroup of G() by A12;
    then reconsider N1=N0 as strict normal Subgroup of G();
    take N1;
    thus N1=N0;
    thus G()./.N1 in GFam2 by A14;
  end;

  A16: GFam3 <> {}
  proof
    consider H0 being strict normal Subgroup of G() such that
    B1: P[G()./.H0] by P0;
    G()./.H0 in GFam2 by A14;
    then G()./.H0 in GFam3 by B1;
    hence thesis;
  end;
  A17: GFam2 is finite set;
::>                      *4
  A18: GFam3 is finite set
  proof
    defpred QuoP[object, object] means $1 in GFam1 & ex N0 being normal Subgroup of G() st $1 = N0 & $2 = G()./.N0;
    B1: for x being object st x in GFam1 ex y being object st y in GFam2 & QuoP[x,y]
    proof
      let x be object;
      assume D1: x in GFam1;
      then reconsider x as normal Subgroup of G() by A13;
      take y = G()./.x;
      thus y in GFam2 by A14;
      consider N0 being normal Subgroup of G() such that
      D2: x = N0 and
      D3: y = G()./.x;
      QuoP[x,y] by D1,D2,D3;
      hence thesis;
    end;
    consider f being Function of GFam1,GFam2 such that
    B3: for x being object st x in GFam1 holds QuoP[x,f.x]
    from FUNCT_2:sch 1(B1);
    
    GFam3 c= GFam2 by A14,TARSKI:def 3;
::>                 *4
    hence thesis by A17,FINSET_1:1;
  end;

::  set GFam = {N1 where N1 is strict normal Subgroup of G() : P3[N1]};
  thus C1: P[G()./.K]
  proof
    set n = card Fam;
    set I = n;
    B1: GFam is finite set
    proof
      D1: G() is finite Group;
      then D2: Subgroups G() is finite by GROUP_3:15;
      for H being object
      st H in GFam
      holds H in Subgroups G()
      proof
        let H be object;
        assume E1: H in GFam;
        then consider H0 being Element of Subgroups G() such that
        E2: H = H0 & P3[H0];
        thus H in Subgroups G() by E2;
      end;
      then GFam c= Subgroups G() by TARSKI:def 3;
      hence thesis by D2,FINSET_1:1;
    end;
    then reconsider GFam as finite set;
    B3: for N being Element of GFam holds N is Group
    proof
      let N be Element of GFam;
      D1: N in GFam by A11;
      then consider N0 being Element of Subgroups G() such that
      D2: N = N0 & P3[N0];
      N0 is Subgroup of G() by GROUP_3:def 1;
      then N0 is Group;
      hence thesis by D2;
    end;
    consider F being associative Group-like multMagma-Family of Seg (card GFam)
    such that
    B4: F is one-to-one & (for i being Nat st i in Seg (card GFam) holds ex G being Group st G in GFam & F.i=G)
    by B1,A11,B3,Th58;

    set I = Seg (card GFam); :: indexing set!
    card I = card GFam;
::>                  *4
    
  for G being Group
  for X being set
  st X <> {} & (for A being Element of X
                holds ex N being strict normal Subgroup of G
                st A = the carrier of N)
  for I being set
  st card I = card X
  for F being associative Group-like multMagma-Family of I
  st (for i being Element of I
      holds ex N being strict normal Subgroup of G st the carrier of N in X & F.i = G./.N) &
     (for N being strict normal Subgroup of G st the carrier of N in X
      holds ex i being Element of I st F.i = G./.N)
  holds ex H being Group st H = product F &
                         ex N being strict normal Subgroup of G
                            st the carrier of N = meet X &
                         ex phi being Homomorphism of G,product F
                            st Image(phi),G./.N are_isomorphic

    for A being Element of Fam
::>   *395
    holds ex N0 being strict normal Subgroup of G()
    st A = the carrier of N0
    proof
::>     *396
      let A be Element of Fam;
      consider N0 being strict normal Subgroup of G() such that
      D1: A = the carrier of N0 & P3[N0]
      by A10;
      thus thesis by D1;
    end;
    :: Theorem 55 will be applied here
    then consider P being Group such that
    B5: P = product F and
    B6: ex CapF being strict normal Subgroup of G()
        st the carrier of CapF = meet Fam &
        ex phi being Homomorphism of G(),product F
        st Image(phi),G()./.CapF are_isomorphic
    by B1,B2,B3,B4,Th55;
::>        *144
    consider CapF being strict normal Subgroup of G() such that
    B7: the carrier of CapF = meet Fam and
    B8: ex phi being Homomorphism of G(),product F
        st Image(phi),G()./.CapF are_isomorphic
    by B6;
    B9: K = CapF by A2,B7,GROUP_2:59;
    consider phi being Homomorphism of G(),product F such that
    B10: Image(phi),G()./.CapF are_isomorphic
    by B8;

   :: for I being set for F being associative Group-like multMagma-Family
   :: of I st (for i being Element of I holds P[F.i]) holds P[product F]

    P[product F]
    proof
      for i being Element of I holds ex N0 being strict normal Subgroup
      of G() st the carrier of N0 in Fam & F.i = G()./.N0 by B3;
::>                                                        *4
      for i being Element of I holds P[F.i]
      proof
        let i be Element of I;
        consider N0 being strict normal Subgroup of G() such that
        D1: the carrier of N0 in Fam and
        D2: F.i = G()./.N0
        by B3;
::>      *4
        set A = the carrier of N0;
        consider A0 being Subset of G() such that
        D3: A0 = A and
        D4: ex N1 being strict Subgroup of G() st A0 = the carrier of N1
            & P3[N1]
        by D1;
        consider N1 being strict Subgroup of G() such that
        D5: A0 = the carrier of N1 & P3[N1]
        by D4;
        the carrier of N0 = A0 by D3
          .= the carrier of N1 by D5;
        then N1 = N0 by GROUP_2:59;
        then P3[N0] by D5;
        then P[G()./.N0];
        hence P[F.i] by D2;
      end;
      hence thesis by P5;
    end;

    then P[Image(phi)] by P2;
    then P[G()./.CapF] by B10,P1;
    hence P[G()./.K] by B9,B10;
  end;
  thus C2: for N being strict normal Subgroup of G()
           holds P[G()./.N] iff K is Subgroup of N
  proof
    let N be strict normal Subgroup of G();
    thus P[G()./.N] implies K is Subgroup of N by A3;
    assume B1: K is Subgroup of N;
    then N./.((N,K) `*`) is normal Subgroup of G()./.K by GROUP_6:29;
    then consider J being normal Subgroup of G()./.K such that
    B2: J = N./.((N,K) `*`);
    P[G()./.K] by C1;
    then P[J] by P2;
    then B3: P[(G()./.K)./.J] by P4,C1;
    (G()./.K)./.J, G()./.N are_isomorphic by B1,B2,GROUP_6:80;
    hence P[G()./.N] by B3,P1;
  end;

  thus K is characteristic;
::>                      *4
end;
::> 4: This inference is not accepted
::> 144: Unknown label
::> 395: Justification expected
::> 396: Formula expected
::> 403: "such" expected
